
import nesper


echo "ESP_OK: " & $ESP_OK

echo "ESP_OK: " & $(ESP_OK)
echo "ESP_FAIL: " & $(ESP_FAIL)
echo "ESP_ERR_NO_MEM: " & $(ESP_ERR_NO_MEM)
echo "ESP_ERR_INVALID_ARG: " & $(ESP_ERR_INVALID_ARG)
echo "ESP_ERR_INVALID_STATE: " & $(ESP_ERR_INVALID_STATE)
echo "ESP_ERR_INVALID_SIZE: " & $(ESP_ERR_INVALID_SIZE)
echo "ESP_ERR_NOT_FOUND: " & $(ESP_ERR_NOT_FOUND)
echo "ESP_ERR_NOT_SUPPORTED: " & $(ESP_ERR_NOT_SUPPORTED)
echo "ESP_ERR_TIMEOUT: " & $(ESP_ERR_TIMEOUT)
echo "ESP_ERR_INVALID_RESPONSE: " & $(ESP_ERR_INVALID_RESPONSE)
echo "ESP_ERR_INVALID_CRC: " & $(ESP_ERR_INVALID_CRC)
echo "ESP_ERR_INVALID_VERSION: " & $(ESP_ERR_INVALID_VERSION)
echo "ESP_ERR_INVALID_MAC: " & $(ESP_ERR_INVALID_MAC)
echo "ESP_ERR_WIFI_BASE: " & $(ESP_ERR_WIFI_BASE)
echo "ESP_ERR_MESH_BASE: " & $(ESP_ERR_MESH_BASE)
echo "ESP_ERR_FLASH_BASE: " & $(ESP_ERR_FLASH_BASE)
