/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw;
typedef struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw;

/* section: NIM_merge_TYPES */
struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw {NI64 seconds;
NI nanosecond;
};
typedef NU8 tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ;
typedef NI64 tyArray__pDfjTbtkTNjmi9bTcaNV32Q[8];

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(NI64, convert__2z1a0DRE31bT73xgVvBfQAtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI64 quantity);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NF, toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem)(NI64 i);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x);
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NI, convert__vsrmXCcg8GubJb67VXeq4wtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a, NI64 b, NI64* res);
static N_INLINE(NI, convert__bBJ7N1GpubC85YlnXz3nHgtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, normalize__JK8O6vJVu4WsESmu0kL4aQ)(NI64 seconds, NI64 nanoseconds);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE NIM_CONST tyArray__pDfjTbtkTNjmi9bTcaNV32Q unitWeights__cpugRVHYEC9bUpLa71eZMsQ = {IL64(1),
IL64(1000),
IL64(1000000),
IL64(1000000000),
IL64(60000000000),
IL64(3600000000000),
IL64(86400000000000),
IL64(604800000000000)}
;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* utcInstance__oeKVHn4dFpBJO35HhEkelw;
N_LIB_PRIVATE NIM_THREADVAR tyObject_TimezonecolonObjectType___F8OvqlxXyGXRSiK9c1fCDVw* localInstance__cLtN9cK9bCe6IPhJ3UFNLNKA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 123 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (a == (IL64(-9223372036854775807) - IL64(1)));		if (!(T3_)) goto LA4_;

#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (b == IL64(-1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 120 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = (NI64)(a / b);	}
	LA1_: ;
	return result;}

#line 549 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 551 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 557 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 1405 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NF, toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem)(NI64 i) {	NF result;	nimfr_("toBiggestFloat", "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = (NF)0;
#line 1406 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(1406, "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = ((NF) (i));	popFrame();	return result;}

#line 1490 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x) {	NF result;	result = (NF)0;
#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	{
#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		if (!(x < 0.0)) goto LA3_;

#line 1491 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		result = -(x);	}
	goto LA1_;
	LA3_: ;
	{		result = x;	}
	LA1_: ;
	return result;}

#line 111 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimMulInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	NI64 r;	NF floatProd;	NF T1_;	NF T2_;	NF resAsFloat;	result = (NIM_BOOL)0;
#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 90 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI64) ((NU64)((NU64)(((NU64) (a))) * (NU64)(((NU64) (b))))));
#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	T1_ = (NF)0;	T1_ = toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem(a);
#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 91 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	T2_ = (NF)0;	T2_ = toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem(b);	floatProd = ((NF)(T1_) * (NF)(T2_));
#line 92 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 92 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	resAsFloat = toBiggestFloat__hTpm9cXKgh17pxyZUsNnUyQsystem(r);
#line 95 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{
#line 95 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		if (!(resAsFloat == floatProd)) goto LA5_;

#line 96 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA3_;
	LA5_: ;
	{
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		{			NF T10_;			NF T11_;
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			T10_ = (NF)0;			T10_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(((NF)(resAsFloat) - (NF)(floatProd)));
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			T11_ = (NF)0;			T11_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(floatProd);			if (!(((NF)(3.2000000000000000e+01) * (NF)(T10_)) <= T11_)) goto LA12_;

#line 106 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			(*res) = r;		}
		goto LA8_;
		LA12_: ;
		{
#line 108 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
			result = NIM_TRUE;		}
		LA8_: ;
	}
	LA3_: ;
	return result;}

#line 399 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
static N_INLINE(NI64, convert__2z1a0DRE31bT73xgVvBfQAtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI64 quantity) {	NI64 result;	nimfr_("convert", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");{	result = (NI64)0;
#line 401 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(401, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(407, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_2;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_3;
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(unitFrom < unitTo)) goto LA3_;

#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(408, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_2)) { raiseOverflow(); goto BeforeRet_;};		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_2) == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(quantity, (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_2), &TM__6NbDwwj5FY059b1gz2AsAZQ_3)) { raiseOverflow(); goto BeforeRet_;};		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_3);	}
	goto LA1_;
	LA3_: ;
	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_4;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_5;
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(410, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_4)) { raiseOverflow(); goto BeforeRet_;};		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_4), quantity, &TM__6NbDwwj5FY059b1gz2AsAZQ_5)) { raiseOverflow(); goto BeforeRet_;};		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_5);	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 53 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	NI64 r;	result = (NIM_BOOL)0;
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI64) ((NU64)((NU64)(((NU64) (a))) + (NU64)(((NU64) (b))))));
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ a));		if (T3_) goto LA4_;

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;

#line 48 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 399 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
static N_INLINE(NI, convert__vsrmXCcg8GubJb67VXeq4wtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity) {	NI result;	nimfr_("convert", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");{	result = (NI)0;
#line 401 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(401, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(407, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_7;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_8;
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(unitFrom < unitTo)) goto LA3_;

#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(408, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_7)) { raiseOverflow(); goto BeforeRet_;};		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_7) == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(((NI64) (quantity)), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_7), &TM__6NbDwwj5FY059b1gz2AsAZQ_8)) { raiseOverflow(); goto BeforeRet_;};		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_8)) < ((NI) (-2147483647 -1)) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_8)) > ((NI) 2147483647)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_8), ((NI) (-2147483647 -1)), ((NI) 2147483647)); goto BeforeRet_;}		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_8)));	}
	goto LA1_;
	LA3_: ;
	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_9;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_10;
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(410, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_9)) { raiseOverflow(); goto BeforeRet_;};		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_9), ((NI64) (quantity)), &TM__6NbDwwj5FY059b1gz2AsAZQ_10)) { raiseOverflow(); goto BeforeRet_;};		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_10)) < ((NI) (-2147483647 -1)) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_10)) > ((NI) 2147483647)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_10), ((NI) (-2147483647 -1)), ((NI) 2147483647)); goto BeforeRet_;}		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_10)));	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 64 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	NI r;	result = (NIM_BOOL)0;
#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;

#line 60 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 65 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimSubInt64)(NI64 a, NI64 b, NI64* res) {	NIM_BOOL result;	NI64 r;	result = (NIM_BOOL)0;
#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 58 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI64) ((NU64)((NU64)(((NU64) (a))) - (NU64)(((NU64) (b))))));
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ a));		if (T3_) goto LA4_;

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 59 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (IL64(0) <= (NI64)(r ^ (NI64)((NU64) ~(b))));		LA4_: ;
		if (!T3_) goto LA5_;

#line 60 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 62 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 399 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
static N_INLINE(NI, convert__bBJ7N1GpubC85YlnXz3nHgtimes)(tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitFrom, tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ unitTo, NI quantity) {	NI result;	nimfr_("convert", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");{	result = (NI)0;
#line 401 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(401, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(407, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_13;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_14;
#line 407 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(unitFrom < unitTo)) goto LA3_;

#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(408, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 408 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_13)) { raiseOverflow(); goto BeforeRet_;};		if ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_13) == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(((NI64) (quantity)), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_13), &TM__6NbDwwj5FY059b1gz2AsAZQ_14)) { raiseOverflow(); goto BeforeRet_;};		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14)) < ((NI) 0) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14)) > ((NI) 999999999)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14), ((NI) 0), ((NI) 999999999)); goto BeforeRet_;}		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_14)));	}
	goto LA1_;
	LA3_: ;
	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_15;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_16;
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(410, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 410 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0] == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt64(unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitFrom)- 0], unitWeights__cpugRVHYEC9bUpLa71eZMsQ[(unitTo)- 0], &TM__6NbDwwj5FY059b1gz2AsAZQ_15)) { raiseOverflow(); goto BeforeRet_;};		if (nimMulInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_15), ((NI64) (quantity)), &TM__6NbDwwj5FY059b1gz2AsAZQ_16)) { raiseOverflow(); goto BeforeRet_;};		if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_16)) < ((NI) 0) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_16)) > ((NI) 999999999)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_16), ((NI) 0), ((NI) 999999999)); goto BeforeRet_;}		result = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_16)));	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 424 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 655 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
N_LIB_PRIVATE N_NIMCALL(NI64, inMilliseconds__df0d89cDnRIju9aB6p1W1qVA)(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw dur) {	NI64 result;	NIM_BOOL correctionX60gensym21990230_;	NIM_BOOL T1_;NIM_BOOL* nimErr_;	nimfr_("inMilliseconds", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");{nimErr_ = nimErrorFlag();	result = (NI64)0;
#line 656 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(656, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(608, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (NIM_BOOL)0;
#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (dur.seconds < IL64(0));	if (!(T1_)) goto LA2_;

#line 608 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (((NI) 0) < ((NI) (dur.nanosecond)));	LA2_: ;
	correctionX60gensym21990230_ = T1_;
#line 612 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(612, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_6;		NI64 T7_;		NI T8_;		NI TM__6NbDwwj5FY059b1gz2AsAZQ_11;		NI T9_;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_12;		if (!correctionX60gensym21990230_) goto LA5_;

#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(613, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (nimAddInt64(dur.seconds, IL64(1), &TM__6NbDwwj5FY059b1gz2AsAZQ_6)) { raiseOverflow(); goto BeforeRet_;};
#line 613 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T7_ = (NI64)0;		T7_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_6));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 614 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(614, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 615 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(615, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 615 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 615 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T8_ = (NI)0;		T8_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (nimSubInt(T8_, ((NI) (dur.nanosecond)), &TM__6NbDwwj5FY059b1gz2AsAZQ_11)) { raiseOverflow(); goto BeforeRet_;};
#line 614 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(614, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");		T9_ = (NI)0;		T9_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), (NI)(TM__6NbDwwj5FY059b1gz2AsAZQ_11));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (nimSubInt64(T7_, ((NI64) (T9_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_12)) { raiseOverflow(); goto BeforeRet_;};		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_12);	}
	goto LA3_;
	LA5_: ;
	{		NI64 T11_;		NI T12_;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_17;
#line 617 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(617, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 617 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 617 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T11_ = (NI64)0;		T11_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), dur.seconds);		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 618 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(618, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 618 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T12_ = (NI)0;		T12_ = convert__bBJ7N1GpubC85YlnXz3nHgtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), dur.nanosecond);		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (nimAddInt64(T11_, ((NI64) (T12_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_17)) { raiseOverflow(); goto BeforeRet_;};		result = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_17);	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 22 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 412 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, normalize__JK8O6vJVu4WsESmu0kL4aQ)(NI64 seconds, NI64 nanoseconds) {	tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw result;	NI64 T1_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_30;	NI64 nanosecond;	NI T2_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_31;NIM_BOOL* nimErr_;	nimfr_("normalize", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw));
#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(416, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 416 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (NI64)0;	T1_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), nanoseconds);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64(seconds, T1_, &TM__6NbDwwj5FY059b1gz2AsAZQ_30)) { raiseOverflow(); goto BeforeRet_;};	result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_30);
#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(417, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 417 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T2_ = (NI)0;	T2_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (((NI64) (T2_)) == 0){ raiseDivByZero(); goto BeforeRet_;}	if (nimModInt64(nanoseconds, ((NI64) (T2_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_31)) { raiseOverflow(); goto BeforeRet_;};	nanosecond = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_31);
#line 418 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(418, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	{		NI T7_;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_32;		NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_33;
#line 418 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		if (!(nanosecond < IL64(0))) goto LA5_;

#line 419 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(419, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 419 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 419 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		T7_ = (NI)0;		T7_ = convert__vsrmXCcg8GubJb67VXeq4wtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((NI) 1));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (nimAddInt64(nanosecond, ((NI64) (T7_)), &TM__6NbDwwj5FY059b1gz2AsAZQ_32)) { raiseOverflow(); goto BeforeRet_;};		nanosecond = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_32);
#line 420 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
		nimln_(420, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");		if (nimSubInt64(result.seconds, ((NI) 1), &TM__6NbDwwj5FY059b1gz2AsAZQ_33)) { raiseOverflow(); goto BeforeRet_;};		result.seconds = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_33);	}
	LA5_: ;

#line 421 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(421, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	if ((nanosecond) < ((NI) (-2147483647 -1)) || (nanosecond) > ((NI) 2147483647)){ raiseRangeErrorI(nanosecond, ((NI) (-2147483647 -1)), ((NI) 2147483647)); goto BeforeRet_;}	if ((((NI) (nanosecond))) < ((NI) 0) || (((NI) (nanosecond))) > ((NI) 999999999)){ raiseRangeErrorI(((NI) (nanosecond)), ((NI) 0), ((NI) 999999999)); goto BeforeRet_;}	result.nanosecond = ((NI) (((NI) (nanosecond))));	}BeforeRet_: ;
	popFrame();	return result;}

#line 579 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, initDuration__wcR3zetvspAUsyuvWZ07Xg)(NI64 nanoseconds, NI64 microseconds, NI64 milliseconds, NI64 seconds, NI64 minutes, NI64 hours, NI64 days, NI64 weeks) {	tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw result;	NI64 seconds_2;	NI64 T1_;	NI64 T2_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_18;	NI64 T3_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_19;	NI64 T4_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_20;	NI64 T5_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_21;	NI64 T6_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_22;	NI64 T7_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_23;	NI64 T8_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_24;	NI nanoseconds_2;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_25;	NI64 T9_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_26;	NI64 T10_;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_27;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_28;	NI64 TM__6NbDwwj5FY059b1gz2AsAZQ_29;NIM_BOOL* nimErr_;	nimfr_("initDuration", "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)(&result), sizeof(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw));
#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(587, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 593 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(593, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 592 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(592, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 591 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(591, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 590 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(590, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 589 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(589, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 588 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(588, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(587, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 587 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T1_ = (NI64)0;	T1_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 7), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), weeks);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 588 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(588, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 588 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T2_ = (NI64)0;	T2_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 6), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), days);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64(T1_, T2_, &TM__6NbDwwj5FY059b1gz2AsAZQ_18)) { raiseOverflow(); goto BeforeRet_;};
#line 589 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(589, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 589 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T3_ = (NI64)0;	T3_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 4), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), minutes);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_18), T3_, &TM__6NbDwwj5FY059b1gz2AsAZQ_19)) { raiseOverflow(); goto BeforeRet_;};
#line 590 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(590, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 590 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T4_ = (NI64)0;	T4_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 5), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), hours);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_19), T4_, &TM__6NbDwwj5FY059b1gz2AsAZQ_20)) { raiseOverflow(); goto BeforeRet_;};
#line 591 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(591, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 591 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T5_ = (NI64)0;	T5_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), seconds);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_20), T5_, &TM__6NbDwwj5FY059b1gz2AsAZQ_21)) { raiseOverflow(); goto BeforeRet_;};
#line 592 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(592, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 592 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T6_ = (NI64)0;	T6_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), milliseconds);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_21), T6_, &TM__6NbDwwj5FY059b1gz2AsAZQ_22)) { raiseOverflow(); goto BeforeRet_;};
#line 593 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(593, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 593 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T7_ = (NI64)0;	T7_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 1), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), microseconds);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_22), T7_, &TM__6NbDwwj5FY059b1gz2AsAZQ_23)) { raiseOverflow(); goto BeforeRet_;};
#line 594 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(594, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 594 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T8_ = (NI64)0;	T8_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 3), nanoseconds);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_23), T8_, &TM__6NbDwwj5FY059b1gz2AsAZQ_24)) { raiseOverflow(); goto BeforeRet_;};	seconds_2 = (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_24);
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(595, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(596, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(595, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"

#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	if (IL64(1000) == 0){ raiseDivByZero(); goto BeforeRet_;}	if (nimModInt64(milliseconds, IL64(1000), &TM__6NbDwwj5FY059b1gz2AsAZQ_25)) { raiseOverflow(); goto BeforeRet_;};
#line 595 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T9_ = (NI64)0;	T9_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 2), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_25));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(596, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	if (IL64(1000000) == 0){ raiseDivByZero(); goto BeforeRet_;}	if (nimModInt64(microseconds, IL64(1000000), &TM__6NbDwwj5FY059b1gz2AsAZQ_26)) { raiseOverflow(); goto BeforeRet_;};
#line 596 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	T10_ = (NI64)0;	T10_ = convert__2z1a0DRE31bT73xgVvBfQAtimes(((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 1), ((tyEnum_TimeUnit__52alPn04ElUUbqLeok9b3PQ) 0), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_26));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt64(T9_, T10_, &TM__6NbDwwj5FY059b1gz2AsAZQ_27)) { raiseOverflow(); goto BeforeRet_;};
#line 597 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(597, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");	if (IL64(1000000000) == 0){ raiseDivByZero(); goto BeforeRet_;}	if (nimModInt64(nanoseconds, IL64(1000000000), &TM__6NbDwwj5FY059b1gz2AsAZQ_28)) { raiseOverflow(); goto BeforeRet_;};	if (nimAddInt64((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_27), (NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_28), &TM__6NbDwwj5FY059b1gz2AsAZQ_29)) { raiseOverflow(); goto BeforeRet_;};	if (((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_29)) < ((NI) (-2147483647 -1)) || ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_29)) > ((NI) 2147483647)){ raiseRangeErrorI((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_29), ((NI) (-2147483647 -1)), ((NI) 2147483647)); goto BeforeRet_;}	nanoseconds_2 = ((NI) ((NI64)(TM__6NbDwwj5FY059b1gz2AsAZQ_29)));
#line 599 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	nimln_(599, "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim");
#line 599 "/home/elcritch/.asdf/installs/nim/devel/lib/pure/times.nim"
	result = normalize__JK8O6vJVu4WsESmu0kL4aQ(seconds_2, ((NI64) (nanoseconds_2)));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}
