/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <arpa/inet.h>
#include <netinet/in.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_TYPES */
typedef NIM_CHAR tyArray__Wfh9bjgBQ4UqJsyISUuDSuA[16];

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_VARS */
N_LIB_PRIVATE int SOMAXCONN__0XWtgJz0atYHiEz9b9aVOcQg = ((int) 32);
N_LIB_PRIVATE int MAP_POPULATE__VA0iC4AP6fJAacff09cx89ag = ((int) 0);
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 549 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 551 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 557 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 966 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"
N_LIB_PRIVATE N_NIMCALL(int, IN6_IS_ADDR_V4MAPPED__6KWoyJxz9c9cfnUA9b5aeMx3w)(struct in6_addr* ipv6_address) {	int result;	NU32* bits32;	NIM_BOOL T1_;	NU32 T3_;	nimfr_("IN6_IS_ADDR_V4MAPPED", "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim");{	result = (int)0;
#line 967 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"
	nimln_(967, "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim");	bits32 = ((NU32*) (ipv6_address));
#line 968 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"
	nimln_(968, "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim");
#line 968 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"

#line 968 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"
	T1_ = (NIM_BOOL)0;
#line 968 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"
	T1_ = (bits32[(((NI) 1))- 0] == ((NU32) 0));	if (!(T1_)) goto LA2_;

#line 968 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"

#line 968 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"

#line 968 "/home/elcritch/.asdf/installs/nim/devel/lib/posix/posix.nim"
	T3_ = (NU32)0;	T3_ = htonl(((NU32) 65535));	T1_ = (bits32[(((NI) 2))- 0] == T3_);	LA2_: ;
	result = ((int) (T1_));	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}
