/* Generated by Nim Compiler v1.3.5 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__bl0bSVWGY9awnrUbJL6olrQ)(tySequence__uB9b75OUPRENsBAu4AnoePA x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix);
N_LIB_PRIVATE N_NIMCALL(void, eq___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__iwHTMWG9c27MDj69bdm9bZJBQ)(NimStringV2* s, tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__ARWLtdz6aJCA2LIYS9cFiGQ)(NimStringV2* s, NCSTRING x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__Eys2fLM61EBlquSM8n9cIsw)(NimStringV2* s, NI x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_4};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_7 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_8 = { 8 | NIM_STRLIT_FLAG, "procname" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_9 = {8, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_8};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_10 = { 2 | NIM_STRLIT_FLAG, ": " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_11 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_10};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_12 = { 3 | NIM_STRLIT_FLAG, "nil" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_13 = {3, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_12};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_14 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_15 = { 4 | NIM_STRLIT_FLAG, "line" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_16 = {4, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_15};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_17 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_10};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_18 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_19 = { 8 | NIM_STRLIT_FLAG, "filename" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_20 = {8, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_19};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_21 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_10};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_22 = {3, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_23 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_24 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_23};
static const struct {
  NI cap; NIM_CHAR data[141+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_25 = { 141 | NIM_STRLIT_FLAG, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m(214, 11) `len(a) == L` the length of the seq changed while ite"
"rating over it" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_26 = {141, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_25};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_27 = { 2 | NIM_STRLIT_FLAG, "@[" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_28 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_27};
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_29 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_30 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_31 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_30};

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 11 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 13 "/home/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2138 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
#line 2139 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2139 "/home/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 52 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	NI r;	result = (NIM_BOOL)0;
#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 46 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ a));		if (T3_) goto LA4_;

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 47 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (((NI) 0) <= (NI)(r ^ b));		LA4_: ;
		if (!T3_) goto LA5_;

#line 48 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = r;	}
	goto LA1_;
	LA5_: ;
	{
#line 50 "/home/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	LA1_: ;
	return result;}

#line 80 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 81 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	{		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_2;		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
#line 81 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) < ((NI) 0) || ((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 83 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2))));

#line 84 "/home/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_3);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 549 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 550 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 551 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 554 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 557 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 558 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 85 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 86 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___WrYXAVecSG9ckDg0dVMv4oQ)(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA x) {	NimStringV2 result;	NI count;	nimfr_("$", "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	result.len = 0; result.p = NIM_NIL;
#line 94 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(94, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	result = TM__n49a9aYp5BrbXv9a6OCpJYm0g_5;
#line 96 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(96, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	count = ((NI) 0);
#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(98, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	{
#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		if (!(((NI) 0) < count)) goto LA3_;

#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_7);	}
	LA3_: ;

#line 100 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(100, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), 8);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_9);
#line 101 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(101, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_11);
#line 102 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(102, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	count += ((NI) 1);
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(105, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	{
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		if (!(x.procname == 0)) goto LA7_;

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		prepareAdd((&result), 3);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_13);	}
	goto LA5_;
	LA7_: ;
	{
#line 106 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		nimln_(106, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");
#line 106 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		addQuoted__ARWLtdz6aJCA2LIYS9cFiGQ((&result), x.procname);
	}
	LA5_: ;

#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(98, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	{
#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		if (!(((NI) 0) < count)) goto LA12_;

#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_14);	}
	LA12_: ;

#line 100 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(100, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), 4);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_16);
#line 101 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(101, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_17);
#line 102 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(102, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	count += ((NI) 1);
#line 108 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(108, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");
#line 108 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	addQuoted__Eys2fLM61EBlquSM8n9cIsw((&result), x.line);

#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(98, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	{
#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		if (!(((NI) 0) < count)) goto LA16_;

#line 98 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_18);	}
	LA16_: ;

#line 100 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(100, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), 8);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_20);
#line 101 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(101, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), 2);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_21);
#line 102 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(102, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	count += ((NI) 1);
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(105, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	{
#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		if (!(x.filename == 0)) goto LA20_;

#line 105 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		prepareAdd((&result), 3);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_22);	}
	goto LA18_;
	LA20_: ;
	{
#line 106 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		nimln_(106, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");
#line 106 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
		addQuoted__ARWLtdz6aJCA2LIYS9cFiGQ((&result), x.filename);
	}
	LA18_: ;

#line 114 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(114, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), 1);appendString((&result), TM__n49a9aYp5BrbXv9a6OCpJYm0g_24);	popFrame();	return result;}

#line 424 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 425 "/home/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 117 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__bl0bSVWGY9awnrUbJL6olrQ)(tySequence__uB9b75OUPRENsBAu4AnoePA x, NimStringV2 prefix, NimStringV2 separator, NimStringV2 suffix) {	NimStringV2 result;	NIM_BOOL firstElement;NIM_BOOL* nimErr_;	nimfr_("collectionToString", "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	nimln_(49, "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/home/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
	eq___aBBXmHFBEivKqERloP6zmA_2((&result), prefix);

#line 119 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(119, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	firstElement = NIM_TRUE;	{		tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA* value;		NI i;		NI L;		NI T2_;		value = (tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA*)0;
#line 209 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
		nimln_(209, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");		i = ((NI) 0);
#line 210 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
		nimln_(210, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");
#line 210 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
		T2_ = x.len;		L = T2_;		{
#line 211 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
			nimln_(211, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");			while (1) {
#line 211 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				if (!(i < L)) goto LA4;

#line 120 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
				nimln_(120, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");				value = (&x.p->data[i]);
#line 121 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
				nimln_(121, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");				{					if (!firstElement) goto LA7_;

#line 122 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
					nimln_(122, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");					firstElement = NIM_FALSE;				}
				goto LA5_;
				LA7_: ;
				{
#line 124 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
					nimln_(124, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");					prepareAdd((&result), separator.len + 0);appendString((&result), separator);				}
				LA5_: ;

#line 133 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
				nimln_(133, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");
#line 133 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
				addQuoted__iwHTMWG9c27MDj69bdm9bZJBQ((&result), (*value));

#line 213 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				nimln_(213, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");				i += ((NI) 1);
#line 214 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				nimln_(214, "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.ni"
"m");				{					NI T12_;
#line 214 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 214 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 214 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					T12_ = x.len;					if (!!((T12_ == L))) goto LA13_;

#line 214 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 214 "/home/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__n49a9aYp5BrbXv9a6OCpJYm0g_26);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;				}
				LA13_: ;
			} LA4: ;
		}
	}

#line 134 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(134, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");	prepareAdd((&result), suffix.len + 0);appendString((&result), suffix);	}BeforeRet_: ;
	popFrame();	return result;}

#line 144 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___7AQ19bV7URzlCmoau9c79cWbw)(tySequence__uB9b75OUPRENsBAu4AnoePA x) {	NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("$", "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 150 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	nimln_(150, "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim");
#line 150 "/home/elcritch/.asdf/installs/nim/devel/lib/system/dollars.nim"
	result = collectionToString__bl0bSVWGY9awnrUbJL6olrQ(x, TM__n49a9aYp5BrbXv9a6OCpJYm0g_28, TM__n49a9aYp5BrbXv9a6OCpJYm0g_29, TM__n49a9aYp5BrbXv9a6OCpJYm0g_31);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}
