/* Generated by Nim Compiler v1.3.7 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <stdio.h>
#include <fcntl.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 77 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (NCSTRING)0;
#line 78 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	{
#line 78 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;

#line 78 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		result = "";	}
	goto LA1_;
	LA3_: ;
	{
#line 79 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		result = ((NCSTRING) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 544 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 776 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0) {	int T6_;	int T7_;	nimfr_("echoBinSafe", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");{
#line 787 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(787, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 787 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	flockfile(__stdoutp);
	{		NimStringV2* s;		NI i;		s = (NimStringV2*)0;
#line 8 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
		nimln_(8, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");		i = ((NI) 0);		{
#line 9 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
			nimln_(9, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");			while (1) {				void* T4_;				int T5_;				NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_2;
#line 9 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"

#line 9 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				if (!(i < argsLen_0)) goto LA3;

#line 790 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
				nimln_(790, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");				if ((NU)(i) >= (NU)(argsLen_0)){ raiseIndexError2(i,argsLen_0-1); goto BeforeRet_;}				s = (&args[i]);
#line 794 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
				nimln_(794, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 794 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
				T4_ = (void*)0;				T4_ = ((void*) (nimToCStringConv((*s))));
#line 794 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 794 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
				T5_ = (int)0;				T5_ = fwrite(T4_, ((size_t) ((*s).len)), ((size_t) 1), __stdoutp);				(void)(T5_);

#line 11 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.nim"
				nimln_(11, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators.n"
"im");				if (nimAddInt(i, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_2)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2);			} LA3: ;
		}
	}

#line 796 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(796, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 796 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 796 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	T6_ = (int)0;	T6_ = fwrite(((void*) ("\012")), ((size_t) 1), ((size_t) 1), __stdoutp);	(void)(T6_);

#line 797 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(797, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 797 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 797 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	T7_ = (int)0;	T7_ = fflush(__stdoutp);	(void)(T7_);

#line 799 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(799, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 799 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	funlockfile(__stdoutp);
	}BeforeRet_: ;
	popFrame();}

#line 330 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, setInheritable__avyDiy1HdQrfaD3Ql9b63EQ)(int f, NIM_BOOL inheritable) {	NIM_BOOL result;	NI32 colontmpD_;	NI32 colontmpD__2;	int flags;	int T10_;	nimfr_("setInheritable", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");{	result = (NIM_BOOL)0;	colontmpD_ = (NI32)0;	colontmpD__2 = (NI32)0;
#line 342 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(342, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 342 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	flags = fcntl(f, F_GETFD);
#line 343 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(343, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");	{
#line 343 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		if (!(flags == ((NI32) -1))) goto LA3_;

#line 344 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		nimln_(344, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 344 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		result = NIM_FALSE;		goto BeforeRet_;
	}
	LA3_: ;

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(345, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	{		if (!inheritable) goto LA7_;

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		colontmpD_ = (NI32)(flags & (NI32)((NU32) ~(FD_CLOEXEC)));		flags = colontmpD_;	}
	goto LA5_;
	LA7_: ;
	{
#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 345 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
		colontmpD__2 = (NI32)(flags | FD_CLOEXEC);		flags = colontmpD__2;	}
	LA5_: ;

#line 346 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	nimln_(346, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim");
#line 346 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 346 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 346 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"

#line 346 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/io.nim"
	T10_ = (int)0;	T10_ = fcntl(f, F_SETFD, flags);	result = !((T10_ == ((NI32) -1)));	}BeforeRet_: ;
	popFrame();	return result;}
