/* Generated by Nim Compiler v1.3.7 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <sys/socket.h>
#include <unistd.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <netdb.h>
#include <string.h>
#include <arpa/inet.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
typedef NU8 tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg;
typedef NU8 tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__dTlC27m9c9aWd5dvuePYanug[256];
typedef NIM_CHAR tyArray__Wfh9bjgBQ4UqJsyISUuDSuA[16];
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {  Exception Sup;};
struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw {  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(NIM_BOOL, setInheritable__dNsSmrKPL29c9c9acyIgu5J2wnativesockets)(int s, NIM_BOOL inheritable);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, setInheritable__avyDiy1HdQrfaD3Ql9b63EQ)(int f, NIM_BOOL inheritable);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__8c1w8B7fpSuB4Dgr5LHVJA)(int socket);
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket__XMhukDsWurFLge2YkET1SQ)(int domain, int sockType, int protocol, NIM_BOOL inheritable);
N_LIB_PRIVATE N_NIMCALL(int, toInt__na0alpTcWAzTnn2v04w1CQ)(tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg domain);
N_LIB_PRIVATE N_NIMCALL(int, toInt__AuveeRAdmuTXERHtCv4MPg)(tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw typ);
N_LIB_PRIVATE N_NIMCALL(int, toInt__7Zb9bURWntNcBAaEQ9aEZK9bQ)(tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg p);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__CWyPYlyH9a6rAuZckFyVxPA)(NI32 errorCode, NimStringV2 additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__9bUWNxbcGnToMWA9b79aTXLIw)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___RkX9btpg5sQIaP8yYXB6tbA)(NU64 x);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src);
N_NIMCALL(NimStringV2, mnewString)(NI len);
static N_INLINE(NIM_BOOL, eqeq___aqip9cmQIuefPKdd25wuEEwsystem)(NCSTRING x, NCSTRING y);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__iGg0RIKceRvsmvq8FUHOEw)(NimStringV2 s, NI first);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_3 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_4 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_5 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_6 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_7 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8 = { 4 | NIM_STRLIT_FLAG, "unix" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_9 = {4, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8};
extern TNimTypeV2 NTIv2__iLZrPn9anoh9ad1MmO0RczFw_;
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_10 = { 38 | NIM_STRLIT_FLAG, "Unknown socket family in getAddrString" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11 = {38, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_10};

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NIM_CONST int osInvalidSocket__voz9aUXu8jtRbvGZZJHNE8w = ((int) -1);
N_LIB_PRIVATE int nativeAfInet__rQwsjQjVqXvdaL9aZofzWwg;
N_LIB_PRIVATE int nativeAfInet6__Da6PongZL9aJxBrf7qeBmfA;
N_LIB_PRIVATE int nativeAfUnix__F0RRmJ8JjfNr6yLSNEn9abA;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 414 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 544 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 226 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
static N_INLINE(NIM_BOOL, setInheritable__dNsSmrKPL29c9c9acyIgu5J2wnativesockets)(int s, NIM_BOOL inheritable) {	NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("setInheritable", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 227 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(227, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 232 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(232, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 232 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	result = setInheritable__avyDiy1HdQrfaD3Ql9b63EQ(s, inheritable);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 216 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(void, close__8c1w8B7fpSuB4Dgr5LHVJA)(int socket) {	int T1_;	nimfr_("close", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 221 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(221, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 221 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 221 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T1_ = (int)0;	T1_ = close(socket);	(void)(T1_);
	popFrame();}

#line 234 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket__XMhukDsWurFLge2YkET1SQ)(int domain, int sockType, int protocol, NIM_BOOL inheritable) {	int result;	int sockType_2;NIM_BOOL* nimErr_;	nimfr_("createNativeSocket", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");{nimErr_ = nimErrorFlag();	result = (int)0;
#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(243, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	sockType_2 = sockType;
#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(248, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	result = socket(domain, sockType_2, protocol);
#line 250 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(250, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	{		NIM_BOOL T3_;
#line 250 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 250 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 250 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T3_ = (NIM_BOOL)0;		T3_ = setInheritable__dNsSmrKPL29c9c9acyIgu5J2wnativesockets(result, inheritable);		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (!!(T3_)) goto LA4_;

#line 251 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(251, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 251 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		close__8c1w8B7fpSuB4Dgr5LHVJA(result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 252 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(252, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 252 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		result = osInvalidSocket__voz9aUXu8jtRbvGZZJHNE8w;		goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 130 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(int, toInt__na0alpTcWAzTnn2v04w1CQ)(tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg domain) {	int result;	nimfr_("toInt", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	result = (int)0;
#line 131 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(131, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	switch (domain) {
	case ((tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg) 0):
	{
#line 132 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(132, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = AF_UNSPEC;	}
	break;
	case ((tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg) 1):
	{
#line 133 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(133, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = AF_UNIX;	}
	break;
	case ((tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
#line 134 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(134, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = AF_INET;	}
	break;
	case ((tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg) 30):
	{
#line 135 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(135, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = AF_INET6;	}
	break;
	}
	popFrame();	return result;}

#line 146 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(int, toInt__AuveeRAdmuTXERHtCv4MPg)(tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw typ) {	int result;	nimfr_("toInt", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	result = (int)0;
#line 147 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(147, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	switch (typ) {
	case ((tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw) 1):
	{
#line 148 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(148, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = SOCK_STREAM;	}
	break;
	case ((tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw) 2):
	{
#line 149 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(149, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = SOCK_DGRAM;	}
	break;
	case ((tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw) 5):
	{
#line 150 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(150, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = SOCK_SEQPACKET;	}
	break;
	case ((tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw) 3):
	{
#line 151 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(151, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = SOCK_RAW;	}
	break;
	}
	popFrame();	return result;}

#line 153 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(int, toInt__7Zb9bURWntNcBAaEQ9aEZK9bQ)(tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg p) {	int result;	nimfr_("toInt", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	result = (int)0;
#line 154 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(154, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	switch (p) {
	case ((tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg) 6):
	{
#line 155 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(155, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = IPPROTO_TCP;	}
	break;
	case ((tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg) 17):
	{
#line 156 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(156, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = IPPROTO_UDP;	}
	break;
	case ((tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg) 18):
	{
#line 157 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(157, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = IPPROTO_IP;	}
	break;
	case ((tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg) 19):
	{
#line 158 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(158, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = IPPROTO_IPV6;	}
	break;
	case ((tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg) 20):
	{
#line 159 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(159, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = IPPROTO_RAW;	}
	break;
	case ((tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg) 21):
	{
#line 160 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(160, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = IPPROTO_ICMP;	}
	break;
	case ((tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg) 22):
	{
#line 161 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(161, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		result = IPPROTO_ICMPV6;	}
	break;
	}
	popFrame();	return result;}

#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket__F1LPwUDx07eMGH1vFNDzcw)(tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg protocol, NIM_BOOL inheritable) {	int result;	int T1_;	int T2_;	int T3_;NIM_BOOL* nimErr_;	nimfr_("createNativeSocket", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");{nimErr_ = nimErrorFlag();	result = (int)0;
#line 258 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(258, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(262, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T1_ = (int)0;	T1_ = toInt__na0alpTcWAzTnn2v04w1CQ(domain);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T2_ = (int)0;	T2_ = toInt__AuveeRAdmuTXERHtCv4MPg(sockType);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T3_ = (int)0;	T3_ = toInt__7Zb9bURWntNcBAaEQ9aEZK9bQ(protocol);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 262 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	result = createNativeSocket__XMhukDsWurFLge2YkET1SQ(T1_, T2_, T3_, inheritable);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 640 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(void, setBlocking__ksfYDEBjQla9cwhYE9b9ck7ZA)(int s, NIM_BOOL blocking) {	NI x;	int T1_;NIM_BOOL* nimErr_;	nimfr_("setBlocking", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");{nimErr_ = nimErrorFlag();
#line 649 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(649, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 649 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 649 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T1_ = (int)0;	T1_ = fcntl(s, F_GETFL, ((NI) 0));	x = ((NI) (T1_));
#line 650 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(650, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	{		NI32 T6_;
#line 650 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		if (!(x == ((NI) -1))) goto LA4_;

#line 651 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(651, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 651 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 651 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T6_ = (NI32)0;		T6_ = osLastError__9bUWNxbcGnToMWA9b79aTXLIw();		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 651 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		raiseOSError__CWyPYlyH9a6rAuZckFyVxPA(T6_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	goto LA2_;
	LA4_: ;
	{		NI colontmpD_;		NI colontmpD__2;		NI mode;		colontmpD_ = (NI)0;		colontmpD__2 = (NI)0;
#line 653 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(653, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 653 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		{			if (!blocking) goto LA10_;

#line 653 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 653 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 653 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			colontmpD_ = (NI)(x & ((NI) ((NI32)((NU32) ~(O_NONBLOCK)))));			mode = colontmpD_;		}
		goto LA8_;
		LA10_: ;
		{
#line 653 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 653 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			colontmpD__2 = (NI)(x | ((NI) (O_NONBLOCK)));			mode = colontmpD__2;		}
		LA8_: ;

#line 654 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(654, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		{			int T15_;			NI32 T18_;
#line 654 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 654 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 654 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			T15_ = (int)0;			T15_ = fcntl(s, F_SETFL, mode);			if (!(T15_ == ((NI32) -1))) goto LA16_;

#line 655 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(655, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 655 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 655 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			T18_ = (NI32)0;			T18_ = osLastError__9bUWNxbcGnToMWA9b79aTXLIw();			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 655 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			raiseOSError__CWyPYlyH9a6rAuZckFyVxPA(T18_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		}
		LA16_: ;
	}
	LA2_: ;
	}BeforeRet_: ;
	popFrame();}

#line 632 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(void, setSockOptInt__EjxaD4yB3b9a9anuNz5h25Og)(int socket, NI level, NI optname, NI optval) {	int value;NIM_BOOL* nimErr_;	nimfr_("setSockOptInt", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");{nimErr_ = nimErrorFlag();
#line 635 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(635, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	if ((optval) < ((int) (-2147483647 -1)) || (optval) > ((int) 2147483647)){ raiseRangeErrorI(optval, ((int) (-2147483647 -1)), ((int) 2147483647)); goto BeforeRet_;}	value = ((int) (optval));
#line 636 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(636, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	{		int T3_;		NI32 T6_;
#line 637 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(637, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 636 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(636, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		if ((level) < ((int) (-2147483647 -1)) || (level) > ((int) 2147483647)){ raiseRangeErrorI(level, ((int) (-2147483647 -1)), ((int) 2147483647)); goto BeforeRet_;}		if ((optname) < ((int) (-2147483647 -1)) || (optname) > ((int) 2147483647)){ raiseRangeErrorI(optname, ((int) (-2147483647 -1)), ((int) 2147483647)); goto BeforeRet_;}
#line 636 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T3_ = (int)0;		T3_ = setsockopt(socket, ((int) (level)), ((int) (optname)), ((void*) ((&value))), ((socklen_t) 4));		if (!(T3_ < ((NI32) 0))) goto LA4_;

#line 638 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(638, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 638 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 638 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T6_ = (NI32)0;		T6_ = osLastError__9bUWNxbcGnToMWA9b79aTXLIw();		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 638 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		raiseOSError__CWyPYlyH9a6rAuZckFyVxPA(T6_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA4_: ;
	}BeforeRet_: ;
	popFrame();}

#line 22 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 77 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (NCSTRING)0;
#line 78 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	{
#line 78 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;

#line 78 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		result = "";	}
	goto LA1_;
	LA3_: ;
	{
#line 79 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		result = ((NCSTRING) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 278 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo__ANf7QnbfE8nyIlFuWroDcQ)(NimStringV2 address, NU16 port, tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol__dqJ1OqRGclxIMMdSLRzzXg protocol) {	struct addrinfo* result;	NimStringV2 socketPort;	struct addrinfo hints;	int T2_;	int T3_;	int T4_;	NimStringV2 T9_;	int gaiResult;NIM_BOOL* nimErr_;	nimfr_("getAddrInfo", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");{nimErr_ = nimErrorFlag();	result = (struct addrinfo*)0;	socketPort.len = 0; socketPort.p = NIM_NIL;	nimZeroMem((void*)(&hints), sizeof(struct addrinfo));
#line 285 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(285, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	result = NIM_NIL;
#line 286 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(286, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 286 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T2_ = (int)0;	T2_ = toInt__na0alpTcWAzTnn2v04w1CQ(domain);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	hints.ai_family = T2_;
#line 287 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(287, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 287 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T3_ = (int)0;	T3_ = toInt__AuveeRAdmuTXERHtCv4MPg(sockType);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	hints.ai_socktype = T3_;
#line 288 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(288, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 288 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	T4_ = (int)0;	T4_ = toInt__7Zb9bURWntNcBAaEQ9aEZK9bQ(protocol);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	hints.ai_protocol = T4_;
#line 295 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(295, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	{
#line 295 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		if (!(domain == ((tyEnum_Domain__Q79bEtFARvq0ekDNtvj3Vqg) 30))) goto LA7_;

#line 296 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(296, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		hints.ai_flags = AI_V4MAPPED;	}
	LA7_: ;
	T9_.len = 0; T9_.p = NIM_NIL;
#line 297 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(297, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	{
#line 297 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		if (!(sockType == ((tyEnum_SockType__NQT1bItGG2X9byGdrWX7ujw) 3))) goto LA12_;

#line 297 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		socketPort = TM__f9bP3LqjpgpB9cXL8Nnak7tQ_6;	}
	goto LA10_;
	LA12_: ;
	{
#line 297 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 297 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		socketPort = dollar___RkX9btpg5sQIaP8yYXB6tbA(port);	}
	LA10_: ;

#line 298 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(298, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 298 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	gaiResult = getaddrinfo(nimToCStringConv(address), nimToCStringConv(socketPort), (&hints), &result);
#line 299 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(299, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	{		NimStringV2 colontmpD_;		NI32 T20_;		NCSTRING T21_;
#line 299 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 299 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		if (!!((gaiResult == ((NI32) 0)))) goto LA17_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(303, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T20_ = (NI32)0;		T20_ = osLastError__9bUWNxbcGnToMWA9b79aTXLIw();		if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T21_ = (NCSTRING)0;		T21_ = (char *)gai_strerror(gaiResult);		colontmpD_ = cstrToNimstr(T21_);
#line 303 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		raiseOSError__CWyPYlyH9a6rAuZckFyVxPA(T20_, colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA19_;		{			LA19_:;		}
		{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	}
	LA17_: ;
	{		LA1_:;	}
	{
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&socketPort));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 264 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(int, bindAddr__aQyfo03zPWPcHE65m8j1pw)(int socket, struct sockaddr* name, socklen_t namelen) {	int result;	nimfr_("bindAddr", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	result = (int)0;
#line 266 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(266, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 266 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	result = bind(socket, name, namelen);	popFrame();	return result;}

#line 268 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(int, listen__pMPsTdchcqQvJDjLVQV1BQ)(int socket, int backlog) {	int result;	nimfr_("listen", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	result = (int)0;
#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(276, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	result = listen(socket, backlog);	popFrame();	return result;}

#line 2895 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(NIM_BOOL, eqeq___aqip9cmQIuefPKdd25wuEEwsystem)(NCSTRING x, NCSTRING y) {	NIM_BOOL result;	nimfr_("==", "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	result = (NIM_BOOL)0;
#line 2900 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(2900, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	{
#line 2900 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;

#line 2900 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA3_: ;
	{		NIM_BOOL T6_;
#line 2901 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		nimln_(2901, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");		T6_ = (NIM_BOOL)0;
#line 2901 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		T6_ = (x == 0);		if (T6_) goto LA7_;

#line 2901 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		T6_ = (y == 0);		LA7_: ;
		if (!T6_) goto LA8_;

#line 2901 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		result = NIM_FALSE;	}
	goto LA1_;
	LA8_: ;
	{		int T11_;
#line 2902 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		nimln_(2902, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");
#line 2902 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2902 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2902 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
		T11_ = (int)0;		T11_ = strcmp(x, y);		result = (T11_ == ((NI32) 0));	}
	LA1_: ;
	popFrame();	return result;}

#line 48 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {	NI result;	size_t T1_;	result = (NI)0;
#line 50 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 50 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 50 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (size_t)0;	T1_ = strlen(a);	result = ((NI) (T1_));	return result;}

#line 466 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getAddrString__uOW9bK6K9cKk7t9aZ19biq1NhA)(struct sockaddr* sockAddr) {	NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("getAddrString", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 468 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(468, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	{		NCSTRING T5_;
#line 468 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		if (!(((int) ((*sockAddr).sa_family)) == nativeAfInet__rQwsjQjVqXvdaL9aZofzWwg)) goto LA3_;

#line 469 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(469, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 469 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 469 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 469 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T5_ = (NCSTRING)0;		T5_ = inet_ntoa((*((struct sockaddr_in*) (sockAddr))).sin_addr);		result = cstrToNimstr(T5_);	}
	goto LA1_;
	LA3_: ;
	{		int addrLen;		NimStringV2 T9_;		struct in6_addr* addr6;
#line 470 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(470, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		if (!(((int) ((*sockAddr).sa_family)) == nativeAfInet6__Da6PongZL9aJxBrf7qeBmfA)) goto LA7_;

#line 471 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(471, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		addrLen = INET6_ADDRSTRLEN;
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 473 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(473, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		if ((addrLen) < ((NI) 0) || (addrLen) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(addrLen, ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;}
#line 473 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		T9_.len = 0; T9_.p = NIM_NIL;		T9_ = mnewString(((NI) (addrLen)));
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");		eqsink___aBBXmHFBEivKqERloP6zmA_2((&result), T9_);

#line 474 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(474, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		addr6 = (&(*((struct sockaddr_in6*) (sockAddr))).sin6_addr);
#line 476 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(476, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		{			NCSTRING T12_;			NCSTRING T13_;			NIM_BOOL T14_;			NI32 T17_;
#line 477 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(477, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 476 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(476, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");			if ((NU)(((NI) 0)) >= (NU)result.len){ raiseIndexError2(((NI) 0),result.len-1); goto BeforeRet_;}			T12_ = (NCSTRING)0;			T12_ = ((NCSTRING) ((&result.p->data[((NI) 0)])));
#line 477 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(477, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");			if ((result.len) < ((NI32) (-2147483647 -1)) || (result.len) > ((NI32) 2147483647)){ raiseRangeErrorI(result.len, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)); goto BeforeRet_;}
#line 476 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(476, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");			T13_ = (NCSTRING)0;			T13_ = (char *)inet_ntop(AF_INET6, ((void*) (addr6)), T12_, ((NI32) (result.len)));
#line 477 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(477, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");			T14_ = (NIM_BOOL)0;			T14_ = eqeq___aqip9cmQIuefPKdd25wuEEwsystem(T13_, NIM_NIL);			if (!T14_) goto LA15_;

#line 478 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(478, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 478 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 478 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			T17_ = (NI32)0;			T17_ = osLastError__9bUWNxbcGnToMWA9b79aTXLIw();			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 478 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			raiseOSError__CWyPYlyH9a6rAuZckFyVxPA(T17_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_7);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		}
		LA15_: ;

#line 479 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(479, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		{			int T20_;			NimStringV2 T23_;
#line 479 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 479 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 479 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"

#line 479 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			T20_ = (int)0;			T20_ = IN6_IS_ADDR_V4MAPPED(addr6);			if (!!((T20_ == ((NI32) 0)))) goto LA21_;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 480 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(480, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 480 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			T23_.len = 0; T23_.p = NIM_NIL;			T23_ = substr__iGg0RIKceRvsmvq8FUHOEw(result, ((NI) 7));
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");			eqsink___aBBXmHFBEivKqERloP6zmA_2((&result), T23_);
		}
		LA21_: ;

#line 485 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(485, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 485 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		if (((nimToCStringConv(result) ? nimCStrLen(nimToCStringConv(result)) : 0)) < ((NI) 0) || ((nimToCStringConv(result) ? nimCStrLen(nimToCStringConv(result)) : 0)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((nimToCStringConv(result) ? nimCStrLen(nimToCStringConv(result)) : 0), ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;}		setLengthStrV2((&result), ((NI) ((nimToCStringConv(result) ? nimCStrLen(nimToCStringConv(result)) : 0))));	}
	goto LA1_;
	LA7_: ;
	{		tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw* T29_;
#line 488 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(488, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		{
#line 488 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			if (!(((int) ((*sockAddr).sa_family)) == nativeAfUnix__F0RRmJ8JjfNr6yLSNEn9abA)) goto LA27_;

#line 489 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
			nimln_(489, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
			eqsink___aBBXmHFBEivKqERloP6zmA_2((&result), TM__f9bP3LqjpgpB9cXL8Nnak7tQ_9);
			goto BeforeRet_;
		}
		LA27_: ;
		T29_ = (tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw*)0;		T29_ = (tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw*) nimNewObj(sizeof(tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw));		(*T29_).Sup.Sup.Sup.m_type = (&NTIv2__iLZrPn9anoh9ad1MmO0RczFw_);		(*T29_).Sup.Sup.name = "IOError";		(*T29_).Sup.Sup.message = TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11;		(*T29_).Sup.Sup.parent = NIM_NIL;
#line 490 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
		nimln_(490, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");		raiseExceptionEx((Exception*)T29_, "IOError", "getAddrString", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim", 490);		goto BeforeRet_;	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_nativesocketsInit000)(void) {

#line 999999 "generated_not_to_break_here"
{
	nimfr_("nativesockets", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");
#line 110 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(110, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	nativeAfInet__rQwsjQjVqXvdaL9aZofzWwg = AF_INET;
#line 111 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(111, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	nativeAfInet6__Da6PongZL9aJxBrf7qeBmfA = AF_INET6;
#line 112 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets.nim"
	nimln_(112, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/nativesockets"
".nim");	nativeAfUnix__F0RRmJ8JjfNr6yLSNEn9abA = AF_UNIX;	popFrame();}
}

