/* Generated by Nim Compiler v1.3.7 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <stdlib.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tySequence__oKfdUHDH0q5oP14wOM6kug tySequence__oKfdUHDH0q5oP14wOM6kug;
typedef struct tySequence__oKfdUHDH0q5oP14wOM6kug_Content tySequence__oKfdUHDH0q5oP14wOM6kug_Content;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyTuple__5aoVPIWYzahUyBc9bMm0M5w tyTuple__5aoVPIWYzahUyBc9bMm0M5w;
typedef struct tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w;
typedef struct tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w;
typedef struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyTuple__0F3Kz25HWtRatQmCDVHWEA tyTuple__0F3Kz25HWtRatQmCDVHWEA;
typedef struct tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ;

/* section: NIM_merge_TYPES */
struct tySequence__oKfdUHDH0q5oP14wOM6kug {
  NI len; tySequence__oKfdUHDH0q5oP14wOM6kug_Content* p;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {NI rc;
NI rootIdx;
};
struct tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w {NI64 ticks;
};
struct tyTuple__5aoVPIWYzahUyBc9bMm0M5w {
tyObject_MonoTime__FEvFMlkqJiSSGVO6HgTv8w Field0;
tyObject_FuturecolonObjectType___te3W2Tqi7xuJ7rlPtg9al5w* Field1;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyTuple__0F3Kz25HWtRatQmCDVHWEA {
tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__0F3Kz25HWtRatQmCDVHWEA tyUncheckedArray__JDjQWOF6l7jz1gUppkfhwA[1];
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w traceStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w toFree;
NI freed;
NI touched;
};
struct tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ {tySequence__oKfdUHDH0q5oP14wOM6kug data;
};


#ifndef tySequence__oKfdUHDH0q5oP14wOM6kug_Content_PP
#define tySequence__oKfdUHDH0q5oP14wOM6kug_Content_PP
struct tySequence__oKfdUHDH0q5oP14wOM6kug_Content { NI cap; tyTuple__5aoVPIWYzahUyBc9bMm0M5w data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p);
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env);
static N_INLINE(void, add__A2hu7ps9a7fQ6dTDoPajZ5gsystem)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* c, TNimTypeV2* t);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, setLen__SyatCisD7U45BA5ZnVhIUw)(tySequence__oKfdUHDH0q5oP14wOM6kug* s, NI newlen);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(void, pop__RpEY5Gba9bncUhtKKagJungsystem)(tySequence__oKfdUHDH0q5oP14wOM6kug* s, tyTuple__5aoVPIWYzahUyBc9bMm0M5w* Result);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, shrink__3H2mZBabfm9cuqk5CZiyKAQ)(tySequence__oKfdUHDH0q5oP14wOM6kug* x, NI newLen);
static N_INLINE(NI, len__RjQWrCkdfvnNzFdZkV0dRQheapqueue)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ heap);
static N_INLINE(void, X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ heap, NI i, tyTuple__5aoVPIWYzahUyBc9bMm0M5w* Result);
N_LIB_PRIVATE N_NIMCALL(void, eq___9b9cABs7HDEYhIYvbLwaxA6g_2)(tyTuple__5aoVPIWYzahUyBc9bMm0M5w* dest, tyTuple__5aoVPIWYzahUyBc9bMm0M5w src);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___9b9cABs7HDEYhIYvbLwaxA6g)(tyTuple__5aoVPIWYzahUyBc9bMm0M5w* dest, tyTuple__5aoVPIWYzahUyBc9bMm0M5w src);
N_LIB_PRIVATE N_NIMCALL(void, siftup__KT07fwIP1Mswyo2fH5Meeg)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ* heap, NI p);
static N_INLINE(NIM_BOOL, heapCmp__2QyOfd9anp1pOLWfLRbzHQgheapqueue)(tyTuple__5aoVPIWYzahUyBc9bMm0M5w x, tyTuple__5aoVPIWYzahUyBc9bMm0M5w y);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lt___RW9bVkX9a9ciXIGLLL6tauarQ)(tyTuple__5aoVPIWYzahUyBc9bMm0M5w x, tyTuple__5aoVPIWYzahUyBc9bMm0M5w y);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___Y9bafhD7jFz3sLg7tjcG9bdQ)(tyTuple__5aoVPIWYzahUyBc9bMm0M5w* dest);
N_LIB_PRIVATE N_NIMCALL(void, siftdown__Zxh1g3A3MXNfUq88v9arH1w)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ* heap, NI startpos, NI p);

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 544 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 436 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {	NI result;	nimfr_("-%", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");	result = (NI)0;
#line 437 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(437, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");
#line 441 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics.nim"
	nimln_(441, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arithmetics"
".nim");	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));	popFrame();	return result;}

#line 414 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 372 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {	NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("nimDecRefIsLastCyclicDyn", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 373 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
	nimln_(373, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");	{		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;		NI T5_;
#line 373 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"

#line 373 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		if (!!((p == NIM_NIL))) goto LA3_;

#line 374 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		nimln_(374, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arc.nim"
		nimln_(63, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arc.nim");
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p)), ((NI) 8));		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
#line 375 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		nimln_(375, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");		{
#line 375 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"

#line 375 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;

#line 376 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
			nimln_(376, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_2;
#line 379 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
			nimln_(379, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");			if (nimSubInt((*cell).rc, ((NI) 16), &TM__f2bNHCHm2LvO7iSrwQtdiQ_2)) { raiseOverflow(); goto BeforeRet_;};			(*cell).rc = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_2);		}
		LA6_: ;

#line 381 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		nimln_(381, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");
#line 381 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		rememberCycle__LoYD9cYK9aJvrcDizBN64qaQ(result, cell, (*((TNimTypeV2**) (p))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___6249b6bLN3qXx9bLdBAZTdsA)(tySequence__oKfdUHDH0q5oP14wOM6kug* dest) {	NI colontmp_;
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
	colontmp_ = ((NI) 0);	{
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
		while (1) {			NI T3_;
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			T3_ = (*dest).len;			if (!(colontmp_ < T3_)) goto LA2;

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			{				NIM_BOOL T6_;
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
				T6_ = (NIM_BOOL)0;				T6_ = nimDecRefIsLastCyclicDyn((*dest).p->data[colontmp_].Field1);				if (!T6_) goto LA7_;

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
				nimDestroyAndDispose((*dest).p->data[colontmp_].Field1);
			}
			LA7_: ;

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			colontmp_ += ((NI) 1);		} LA2: ;
	}

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) { deallocShared((*dest).p);}}

#line 122 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (a == ((NI) (-2147483647 -1)));		if (!(T3_)) goto LA4_;

#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (b == ((NI) -1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = (NI)(a / b);	}
	LA1_: ;
	return result;}

#line 11 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {	void* T1_;
#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 13 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source, ((size_t) (size)));}

#line 2177 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
#line 2178 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 2178 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimCopyMem(dest, source, size);
}

#line 19 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
static N_INLINE(void, add__A2hu7ps9a7fQ6dTDoPajZ5gsystem)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* c, TNimTypeV2* t) {	tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* colontmp_;	TNimTypeV2* colontmp__2;	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_7;	nimfr_("add", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");{
#line 20 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
	nimln_(20, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");	{		NI TM__f2bNHCHm2LvO7iSrwQtdiQ_3;		NI TM__f2bNHCHm2LvO7iSrwQtdiQ_4;		tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;		NI TM__f2bNHCHm2LvO7iSrwQtdiQ_5;		void* T5_;		void* T6_;		NI TM__f2bNHCHm2LvO7iSrwQtdiQ_6;
#line 20 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		if (!((*s).cap <= (*s).len)) goto LA3_;

#line 21 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		nimln_(21, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");
#line 21 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"

#line 21 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).cap, ((NI) 3), &TM__f2bNHCHm2LvO7iSrwQtdiQ_3)) { raiseOverflow(); goto BeforeRet_;};		if (((NI) 2) == 0){ raiseDivByZero(); goto BeforeRet_;}		if (nimDivInt((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_3), ((NI) 2), &TM__f2bNHCHm2LvO7iSrwQtdiQ_4)) { raiseOverflow(); goto BeforeRet_;};		(*s).cap = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_4);
#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		nimln_(23, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");
#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"

#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).cap, ((NI) 8), &TM__f2bNHCHm2LvO7iSrwQtdiQ_5)) { raiseOverflow(); goto BeforeRet_;};
#line 23 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		T5_ = (void*)0;		T5_ = malloc(((NU) ((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_5))));		d = ((tyTuple__0F3Kz25HWtRatQmCDVHWEA*) (T5_));
#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		nimln_(26, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");		T6_ = (void*)0;		T6_ = ((void*) ((*s).d));
#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s).len, ((NI) 8), &TM__f2bNHCHm2LvO7iSrwQtdiQ_6)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_6)) < ((NI) 0) || ((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_6)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_6), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 26 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) (d)), T6_, ((NI) ((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_6))));

#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		nimln_(28, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");
#line 28 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		free(((void*) ((*s).d)));

#line 31 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
		nimln_(31, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");		(*s).d = d;	}
	LA3_: ;

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
	nimln_(33, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");	colontmp_ = c;
#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
	colontmp__2 = t;
#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
	(*s).d[(*s).len].Field0 = colontmp_;	(*s).d[(*s).len].Field1 = colontmp__2;
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2.nim"
	nimln_(34, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/cellseqs_v2"
".nim");	if (nimAddInt((*s).len, ((NI) 1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_7)) { raiseOverflow(); goto BeforeRet_;};	(*s).len = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_7);	}BeforeRet_: ;
	popFrame();}

#line 99 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env) {	void** p;	nimfr_("nimTraceRefDyn", "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");
#line 100 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
	nimln_(100, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");	p = ((void**) (q));
#line 101 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
	nimln_(101, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");	{		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;		NI T5_;
#line 101 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"

#line 101 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		if (!!(((*p) == NIM_NIL))) goto LA3_;

#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		nimln_(102, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));
#line 103 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		nimln_(103, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arc.nim"
		nimln_(63, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arc.nim");
#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) ((*p))), ((NI) 8));
#line 103 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim"
		nimln_(103, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/orc.nim");		add__A2hu7ps9a7fQ6dTDoPajZ5gsystem((&(*j).traceStack), ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_)), (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
	popFrame();}

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___kLEUiLoDcS19atuouP8VfDw)(tySequence__oKfdUHDH0q5oP14wOM6kug* dest, void* env) {	NI colontmp_;
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
	colontmp_ = ((NI) 0);	{
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
		while (1) {			NI T3_;
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			T3_ = (*dest).len;			if (!(colontmp_ < T3_)) goto LA2;

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			nimTraceRefDyn(&(*dest).p->data[colontmp_].Field1, env);

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			colontmp_ += ((NI) 1);		} LA2: ;
	}
}

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdispose___6249b6bLN3qXx9bLdBAZTdsA_2)(tySequence__oKfdUHDH0q5oP14wOM6kug* dest) {	NI colontmp_;
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
	colontmp_ = ((NI) 0);	{
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
		while (1) {			NI T3_;
#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			T3_ = (*dest).len;			if (!(colontmp_ < T3_)) goto LA2;

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
			colontmp_ += ((NI) 1);		} LA2: ;
	}

#line 1140 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/asyncdispatch.nim"
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) { deallocShared((*dest).p);}}

#line 164 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
N_LIB_PRIVATE N_NIMCALL(void, clear__uwU9c2lsLU9ak4QmYnE6XQuA)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ* heap) {	nimfr_("clear", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 171 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(171, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 171 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	setLen__SyatCisD7U45BA5ZnVhIUw((&(*heap).data), ((NI) 0));
	popFrame();}

#line 22 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 1829 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
static N_INLINE(void, pop__RpEY5Gba9bncUhtKKagJungsystem)(tySequence__oKfdUHDH0q5oP14wOM6kug* s, tyTuple__5aoVPIWYzahUyBc9bMm0M5w* Result) {	NI L;	NI T1_;	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_8;	nimfr_("pop", "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");{
#line 1838 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(1838, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");
#line 1838 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"

#line 1838 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	T1_ = (*s).len;	if (nimSubInt(T1_, ((NI) 1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_8)) { raiseOverflow(); goto BeforeRet_;};	L = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_8);
#line 1840 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(1840, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");
#line 1840 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	if ((NU)(L) >= (NU)(*s).len){ raiseIndexError2(L,(*s).len-1); goto BeforeRet_;}	(*Result).Field0 = (*s).p->data[L].Field0;	(*Result).Field1 = (*s).p->data[L].Field1;	nimZeroMem((void*)(&(*s).p->data[L]), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 1841 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	nimln_(1841, "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim");	if ((L) < ((NI) 0) || (L) > ((NI) 2147483647)){ raiseRangeErrorI(L, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 1841 "/Users/elcritch/.asdf/installs/nim/devel/lib/system.nim"
	shrink__3H2mZBabfm9cuqk5CZiyKAQ(s, ((NI) (L)));
	}BeforeRet_: ;
	popFrame();}

#line 63 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
static N_INLINE(NI, len__RjQWrCkdfvnNzFdZkV0dRQheapqueue)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ heap) {	NI result;	NI T1_;	nimfr_("len", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	result = (NI)0;
#line 64 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(64, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 65 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(65, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	T1_ = heap.data.len;	result = T1_;	popFrame();	return result;}

#line 67 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
static N_INLINE(void, X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ heap, NI i, tyTuple__5aoVPIWYzahUyBc9bMm0M5w* Result) {NIM_BOOL* nimErr_;	nimfr_("[]", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)Result, sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	if ((NU)(i) >= (NU)heap.data.len){ raiseIndexError2(i,heap.data.len-1); goto BeforeRet_;}
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	eq___9b9cABs7HDEYhIYvbLwaxA6g_2(Result, heap.data.p->data[i]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 71 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
static N_INLINE(NIM_BOOL, heapCmp__2QyOfd9anp1pOLWfLRbzHQgheapqueue)(tyTuple__5aoVPIWYzahUyBc9bMm0M5w x, tyTuple__5aoVPIWYzahUyBc9bMm0M5w y) {	NIM_BOOL result;	nimfr_("heapCmp", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");{	result = (NIM_BOOL)0;
#line 72 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(72, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 72 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 72 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	result = lt___RW9bVkX9a9ciXIGLLL6tauarQ(x, y);	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 74 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
N_LIB_PRIVATE N_NIMCALL(void, siftdown__Zxh1g3A3MXNfUq88v9arH1w)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ* heap, NI startpos, NI p) {	tyTuple__5aoVPIWYzahUyBc9bMm0M5w newitem;	NI pos;NIM_BOOL oldNimErrFin4_;NIM_BOOL* nimErr_;	nimfr_("siftdown", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)(&newitem), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 78 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(78, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	pos = p;
#line 79 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(79, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	if ((pos) < ((NI) 0) || (pos) > ((NI) 2147483647)){ raiseRangeErrorI(pos, ((NI) 0), ((NI) 2147483647)); goto LA1_;}
#line 79 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue((*heap), ((NI) (pos)), (&newitem));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	{
#line 82 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		nimln_(82, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");		while (1) {			tyTuple__5aoVPIWYzahUyBc9bMm0M5w parent;			NI parentpos;			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_14;
#line 82 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			if (!(startpos < pos)) goto LA3;
			nimZeroMem((void*)(&parent), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(83, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 83 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			if (nimSubInt(pos, ((NI) 1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_14)) { raiseOverflow(); goto LA4_;};			parentpos = (NI)((NI32)((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_14)) >> (NU32)(((NI) 1)));
#line 84 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(84, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");			if ((parentpos) < ((NI) 0) || (parentpos) > ((NI) 2147483647)){ raiseRangeErrorI(parentpos, ((NI) 0), ((NI) 2147483647)); goto LA4_;}
#line 84 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue((*heap), ((NI) (parentpos)), (&parent));
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(85, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");			{				NIM_BOOL T7_;
#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 85 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				T7_ = (NIM_BOOL)0;				T7_ = heapCmp__2QyOfd9anp1pOLWfLRbzHQgheapqueue(newitem, parent);				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;				if (!T7_) goto LA8_;

#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");				if ((NU)(pos) >= (NU)(*heap).data.len){ raiseIndexError2(pos,(*heap).data.len-1); goto LA4_;}
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				eqsink___9b9cABs7HDEYhIYvbLwaxA6g((&(*heap).data.p->data[pos]), parent);
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				nimln_(86, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");				nimZeroMem((void*)(&parent), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 87 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				nimln_(87, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");				pos = parentpos;			}
			goto LA5_;
			LA8_: ;
			{
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				eqdestroy___Y9bafhD7jFz3sLg7tjcG9bdQ((&parent));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 89 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				nimln_(89, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");				goto LA2;
			}
			LA5_: ;
			{				LA4_:;			}
			{				oldNimErrFin4_ = *nimErr_; *nimErr_ = NIM_FALSE;
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				eqdestroy___Y9bafhD7jFz3sLg7tjcG9bdQ((&parent));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;				*nimErr_ = oldNimErrFin4_;			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;		} LA3: ;
	} LA2: ;

#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	if ((NU)(pos) >= (NU)(*heap).data.len){ raiseIndexError2(pos,(*heap).data.len-1); goto LA1_;}
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	eqsink___9b9cABs7HDEYhIYvbLwaxA6g((&(*heap).data.p->data[pos]), newitem);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	{		LA1_:;	}
	{	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 92 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
N_LIB_PRIVATE N_NIMCALL(void, siftup__KT07fwIP1Mswyo2fH5Meeg)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ* heap, NI p) {	tyTuple__5aoVPIWYzahUyBc9bMm0M5w newitem;	NI endpos;	NI pos;	NI startpos;	NI childpos;	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_9;	NI TM__f2bNHCHm2LvO7iSrwQtdiQ_10;NIM_BOOL* nimErr_;	nimfr_("siftup", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)(&newitem), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 93 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(93, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 93 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	endpos = len__RjQWrCkdfvnNzFdZkV0dRQheapqueue((*heap));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 94 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(94, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	pos = p;
#line 95 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(95, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	startpos = pos;
#line 96 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(96, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	if ((pos) < ((NI) 0) || (pos) > ((NI) 2147483647)){ raiseRangeErrorI(pos, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 96 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue((*heap), ((NI) (pos)), (&newitem));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 98 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(98, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 98 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 98 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	if (nimMulInt(((NI) 2), pos, &TM__f2bNHCHm2LvO7iSrwQtdiQ_9)) { raiseOverflow(); goto BeforeRet_;};	if (nimAddInt((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_9), ((NI) 1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_10)) { raiseOverflow(); goto BeforeRet_;};	childpos = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_10);	{
#line 99 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		nimln_(99, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");		while (1) {			tyTuple__5aoVPIWYzahUyBc9bMm0M5w colontmpD_;			tyTuple__5aoVPIWYzahUyBc9bMm0M5w colontmpD__2;			NI rightpos;			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_11;			tyTuple__5aoVPIWYzahUyBc9bMm0M5w T11_;			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_12;			NI TM__f2bNHCHm2LvO7iSrwQtdiQ_13;
#line 99 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			if (!(childpos < endpos)) goto LA2;
			nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));			nimZeroMem((void*)(&colontmpD__2), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 101 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(101, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 101 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			if (nimAddInt(childpos, ((NI) 1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_11)) { raiseOverflow(); goto BeforeRet_;};			rightpos = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_11);
#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(102, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");			{				NIM_BOOL T5_;				tyTuple__5aoVPIWYzahUyBc9bMm0M5w T7_;				NIM_BOOL T8_;
#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				T5_ = (NIM_BOOL)0;
#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				T5_ = (rightpos < endpos);				if (!(T5_)) goto LA6_;

#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				if ((childpos) < ((NI) 0) || (childpos) > ((NI) 2147483647)){ raiseRangeErrorI(childpos, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue((*heap), ((NI) (childpos)), (&colontmpD_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;				nimZeroMem((void*)(&T7_), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));				T7_.Field0 = colontmpD_.Field0;				T7_.Field1 = colontmpD_.Field1;
#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				if ((rightpos) < ((NI) 0) || (rightpos) > ((NI) 2147483647)){ raiseRangeErrorI(rightpos, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue((*heap), ((NI) (rightpos)), (&colontmpD__2));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 102 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				T8_ = (NIM_BOOL)0;				T8_ = heapCmp__2QyOfd9anp1pOLWfLRbzHQgheapqueue(T7_, colontmpD__2);				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;				T5_ = !(T8_);				LA6_: ;
				if (!T5_) goto LA9_;

#line 103 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
				nimln_(103, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");				childpos = rightpos;			}
			LA9_: ;

#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");			if ((NU)(pos) >= (NU)(*heap).data.len){ raiseIndexError2(pos,(*heap).data.len-1); goto BeforeRet_;}
#line 105 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(105, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");			if ((childpos) < ((NI) 0) || (childpos) > ((NI) 2147483647)){ raiseRangeErrorI(childpos, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 105 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimZeroMem((void*)(&T11_), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));			X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue((*heap), ((NI) (childpos)), (&T11_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");			eqsink___9b9cABs7HDEYhIYvbLwaxA6g((&(*heap).data.p->data[pos]), T11_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 106 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(106, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");			pos = childpos;
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(107, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			if (nimMulInt(((NI) 2), pos, &TM__f2bNHCHm2LvO7iSrwQtdiQ_12)) { raiseOverflow(); goto BeforeRet_;};			if (nimAddInt((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_12), ((NI) 1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_13)) { raiseOverflow(); goto BeforeRet_;};			childpos = (NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_13);
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			eqdestroy___Y9bafhD7jFz3sLg7tjcG9bdQ((&colontmpD__2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
			eqdestroy___Y9bafhD7jFz3sLg7tjcG9bdQ((&colontmpD_));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		} LA2: ;
	}

#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	if ((NU)(pos) >= (NU)(*heap).data.len){ raiseIndexError2(pos,(*heap).data.len-1); goto BeforeRet_;}
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	eqsink___9b9cABs7HDEYhIYvbLwaxA6g((&(*heap).data.p->data[pos]), newitem);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 111 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(111, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 111 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	siftdown__Zxh1g3A3MXNfUq88v9arH1w(heap, startpos, pos);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 118 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
N_LIB_PRIVATE N_NIMCALL(void, pop__TlOaAtzBOZyVC1usll2RJQ)(tyObject_HeapQueue__mgfFdry9aKsRMW9au5u9bSpOQ* heap, tyTuple__5aoVPIWYzahUyBc9bMm0M5w* Result) {	tyTuple__5aoVPIWYzahUyBc9bMm0M5w lastelt;NIM_BOOL* nimErr_;	nimfr_("pop", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)Result, sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));	nimZeroMem((void*)(&lastelt), sizeof(tyTuple__5aoVPIWYzahUyBc9bMm0M5w));
#line 121 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(121, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 121 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	pop__RpEY5Gba9bncUhtKKagJungsystem((&(*heap).data), (&lastelt));

#line 122 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
	nimln_(122, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");	{		NI T3_;
#line 122 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 122 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"

#line 122 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		T3_ = (NI)0;		T3_ = len__RjQWrCkdfvnNzFdZkV0dRQheapqueue((*heap));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (!(((NI) 0) < T3_)) goto LA4_;

#line 123 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		nimln_(123, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 123 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		X5BX5D___UJ0Pc8uyocnxAC22hPdw4gheapqueue((*heap), ((NI) 0), Result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");		if ((NU)(((NI) 0)) >= (NU)(*heap).data.len){ raiseIndexError2(((NI) 0),(*heap).data.len-1); goto BeforeRet_;}
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		eqsink___9b9cABs7HDEYhIYvbLwaxA6g((&(*heap).data.p->data[((NI) 0)]), lastelt);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 125 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		nimln_(125, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 125 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		siftup__KT07fwIP1Mswyo2fH5Meeg(heap, ((NI) 0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	goto LA1_;
	LA4_: ;
	{
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		nimln_(68, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/h"
"eapqueue.nim");
#line 68 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/collections/heapqueue.nim"
		eqsink___9b9cABs7HDEYhIYvbLwaxA6g(Result, lastelt);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();}
