/* Generated by Nim Compiler v1.3.7 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__C0YoABEefTaYbWLv9aVOzZA)(NimStringV2* s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_CHAR, toLower__eK9b2e49aPf4wAIdUwhbmZsQparseutils)(NIM_CHAR c);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);

/* section: NIM_merge_VARS */
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */

#line 143 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
#line 144 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	{		NIM_BOOL T3_;
#line 144 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		T3_ = (NIM_BOOL)0;
#line 144 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 144 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		T3_ = !(((*s).p == NIM_NIL));		if (!(T3_)) goto LA4_;

#line 144 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 144 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));		LA4_: ;
		if (!T3_) goto LA5_;

#line 145 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 145 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
		nimPrepareStrMutationImpl__C0YoABEefTaYbWLv9aVOzZA(s);
	}
	LA5_: ;
}

#line 544 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 313 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(void, fastSubstr__a88zu6ztJ3SBDTHcnqFjsg)(NimStringV2 s, NimStringV2* token, NI start, NI length) {	nimfr_("fastSubstr", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");{
#line 314 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(314, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	if ((length) < ((NI) 0) || (length) > ((NI) 2147483647)){ raiseRangeErrorI(length, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}	setLengthStrV2((&(*token)), ((NI) (length)));	{		NI i;		NI i_2;		i = (NI)0;
#line 106 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
		nimln_(106, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");		i_2 = ((NI) 0);		{
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
			nimln_(107, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");			while (1) {				NI TM__vI9aZNKIcImom6dDyKXW1ZA_2;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_3;
#line 107 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				if (!(i_2 < length)) goto LA3;

#line 315 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				nimln_(315, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");				i = i_2;				if ((NU)(i) >= (NU)(*token).len){ raiseIndexError2(i,(*token).len-1); goto BeforeRet_;}				nimPrepareStrMutationV2((&(*token)));
#line 315 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 315 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				if (nimAddInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_2)) { raiseOverflow(); goto BeforeRet_;};				if ((NU)((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2)) >= (NU)s.len){ raiseIndexError2((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2),s.len-1); goto BeforeRet_;}				(*token).p->data[i] = s.p->data[(NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2)];
#line 109 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1.nim"
				nimln_(109, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/iterators_1"
".nim");				if (nimAddInt(i_2, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_3)) { raiseOverflow(); goto BeforeRet_;};				i_2 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_3);			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();}

#line 59 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
static N_INLINE(NIM_CHAR, toLower__eK9b2e49aPf4wAIdUwhbmZsQparseutils)(NIM_CHAR c) {	NIM_CHAR result;	NIM_CHAR colontmpD_;	NIM_CHAR colontmpD__2;	nimfr_("toLower", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");{	result = (NIM_CHAR)0;	colontmpD_ = (NIM_CHAR)0;	colontmpD__2 = (NIM_CHAR)0;
#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(60, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	{		NI TM__vI9aZNKIcImom6dDyKXW1ZA_5;		NI TM__vI9aZNKIcImom6dDyKXW1ZA_6;
#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3_;

#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		if (nimSubInt(((NU8)(c)), ((NI) 65), &TM__vI9aZNKIcImom6dDyKXW1ZA_5)) { raiseOverflow(); goto BeforeRet_;};		if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_5), ((NI) 97), &TM__vI9aZNKIcImom6dDyKXW1ZA_6)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_6)) < ((NI) 0) || ((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_6)) > ((NI) 255)){ raiseRangeErrorI((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_6), ((NI) 0), ((NI) 255)); goto BeforeRet_;}		colontmpD_ = ((NIM_CHAR) (((NI) ((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_6)))));		result = colontmpD_;	}
	goto LA1_;
	LA3_: ;
	{
#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		colontmpD__2 = c;		result = colontmpD__2;	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 414 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 270 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, skipIgnoreCase__Z630VYBL4pZDWlOyn05K5w)(NimStringV2 s, NimStringV2 token, NI start) {	NI result;NIM_BOOL* nimErr_;	nimfr_("skipIgnoreCase", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 275 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(275, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	result = ((NI) 0);	{
#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		nimln_(276, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");		while (1) {			NIM_BOOL T3_;			NIM_BOOL T4_;			NI TM__vI9aZNKIcImom6dDyKXW1ZA_4;			NI TM__vI9aZNKIcImom6dDyKXW1ZA_7;			NIM_CHAR T7_;			NIM_CHAR T8_;			NI TM__vI9aZNKIcImom6dDyKXW1ZA_8;
#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T3_ = (NIM_BOOL)0;
#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T4_ = (NIM_BOOL)0;
#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if (nimAddInt(start, result, &TM__vI9aZNKIcImom6dDyKXW1ZA_4)) { raiseOverflow(); goto BeforeRet_;};
#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T4_ = ((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4) < s.len);			if (!(T4_)) goto LA5_;

#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 276 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T4_ = (result < token.len);			LA5_: ;
			T3_ = T4_;			if (!(T3_)) goto LA6_;

#line 277 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			nimln_(277, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 277 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 277 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if (nimAddInt(result, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_7)) { raiseOverflow(); goto BeforeRet_;};			if ((NU)((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_7)) >= (NU)s.len){ raiseIndexError2((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_7),s.len-1); goto BeforeRet_;}
#line 277 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T7_ = (NIM_CHAR)0;			T7_ = toLower__eK9b2e49aPf4wAIdUwhbmZsQparseutils(s.p->data[(NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_7)]);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 277 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if ((NU)(result) >= (NU)token.len){ raiseIndexError2(result,token.len-1); goto BeforeRet_;}
#line 277 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T8_ = (NIM_CHAR)0;			T8_ = toLower__eK9b2e49aPf4wAIdUwhbmZsQparseutils(token.p->data[result]);			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;			T3_ = ((NU8)(T7_) == (NU8)(T8_));			LA6_: ;
			if (!T3_) goto LA2;

#line 277 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if (nimAddInt(result, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_8)) { raiseOverflow(); goto BeforeRet_;};			result = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_8);		} LA2: ;
	}

#line 278 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(278, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	{
#line 278 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 278 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 278 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		if (!!((result == token.len))) goto LA11_;

#line 278 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		result = ((NI) 0);	}
	LA11_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 122 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {	NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (a == ((NI) (-2147483647 -1)));		if (!(T3_)) goto LA4_;

#line 117 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		T3_ = (b == ((NI) -1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"

#line 120 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/integerops.nim"
		(*res) = (NI)(a / b);	}
	LA1_: ;
	return result;}

#line 480 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
N_LIB_PRIVATE N_NIMCALL(NI, parseSaturatedNatural__hGWFPKYRsDcYFCjZLM9acZw)(NimStringV2 s, NI* b, NI start) {	NI result;	NI i;	nimfr_("parseSaturatedNatural", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");{	result = (NI)0;
#line 490 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(490, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	i = start;
#line 491 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(491, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	{		NIM_BOOL T3_;		NI TM__vI9aZNKIcImom6dDyKXW1ZA_9;
#line 491 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		T3_ = (NIM_BOOL)0;
#line 491 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 491 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		T3_ = (i < s.len);		if (!(T3_)) goto LA4_;

#line 491 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		T3_ = ((NU8)(s.p->data[i]) == (NU8)(43));		LA4_: ;
		if (!T3_) goto LA5_;

#line 491 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_9)) { raiseOverflow(); goto BeforeRet_;};		i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_9);	}
	LA5_: ;

#line 492 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(492, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	{		NIM_BOOL T9_;		NI TM__vI9aZNKIcImom6dDyKXW1ZA_17;
#line 492 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		T9_ = (NIM_BOOL)0;
#line 492 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 492 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		T9_ = (i < s.len);		if (!(T9_)) goto LA10_;

#line 492 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}		T9_ = (((NU8)(s.p->data[i])) >= ((NU8)(48)) && ((NU8)(s.p->data[i])) <= ((NU8)(57)));		LA10_: ;
		if (!T9_) goto LA11_;

#line 493 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		nimln_(493, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");		(*b) = ((NI) 0);		{
#line 494 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			nimln_(494, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");			while (1) {				NIM_BOOL T15_;				NI c;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_10;				NI TM__vI9aZNKIcImom6dDyKXW1ZA_15;
#line 494 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				T15_ = (NIM_BOOL)0;
#line 494 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 494 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				T15_ = (i < s.len);				if (!(T15_)) goto LA16_;

#line 494 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				T15_ = (((NU8)(s.p->data[i])) >= ((NU8)(48)) && ((NU8)(s.p->data[i])) <= ((NU8)(57)));				LA16_: ;
				if (!T15_) goto LA14;

#line 495 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				nimln_(495, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 495 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 495 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}				if (nimSubInt(((NU8)(s.p->data[i])), ((NI) 48), &TM__vI9aZNKIcImom6dDyKXW1ZA_10)) { raiseOverflow(); goto BeforeRet_;};				c = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_10);
#line 496 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				nimln_(496, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");				{					NI TM__vI9aZNKIcImom6dDyKXW1ZA_11;					NI TM__vI9aZNKIcImom6dDyKXW1ZA_12;					NI TM__vI9aZNKIcImom6dDyKXW1ZA_13;					NI TM__vI9aZNKIcImom6dDyKXW1ZA_14;
#line 496 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 496 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 496 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
					if (nimSubInt(((NI) 2147483647), c, &TM__vI9aZNKIcImom6dDyKXW1ZA_11)) { raiseOverflow(); goto BeforeRet_;};					if (((NI) 10) == 0){ raiseDivByZero(); goto BeforeRet_;}					if (nimDivInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_11), ((NI) 10), &TM__vI9aZNKIcImom6dDyKXW1ZA_12)) { raiseOverflow(); goto BeforeRet_;};					if (!((*b) <= (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_12))) goto LA19_;

#line 497 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
					nimln_(497, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 497 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 497 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
					if (nimMulInt((*b), ((NI) 10), &TM__vI9aZNKIcImom6dDyKXW1ZA_13)) { raiseOverflow(); goto BeforeRet_;};					if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_13), c, &TM__vI9aZNKIcImom6dDyKXW1ZA_14)) { raiseOverflow(); goto BeforeRet_;};					(*b) = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_14);				}
				goto LA17_;
				LA19_: ;
				{
#line 499 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
					nimln_(499, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");					(*b) = ((NI) 2147483647);				}
				LA17_: ;

#line 500 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
				nimln_(500, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");				if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_15)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_15);				{
#line 501 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
					nimln_(501, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");					while (1) {						NIM_BOOL T24_;						NI TM__vI9aZNKIcImom6dDyKXW1ZA_16;
#line 501 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
						T24_ = (NIM_BOOL)0;
#line 501 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 501 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
						T24_ = (i < s.len);						if (!(T24_)) goto LA25_;

#line 501 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
						if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}						T24_ = ((NU8)(s.p->data[i]) == (NU8)(95));						LA25_: ;
						if (!T24_) goto LA23;

#line 501 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
						if (nimAddInt(i, ((NI) 1), &TM__vI9aZNKIcImom6dDyKXW1ZA_16)) { raiseOverflow(); goto BeforeRet_;};						i = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_16);					} LA23: ;
				}
			} LA14: ;
		}

#line 502 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		nimln_(502, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 502 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		if (nimSubInt(i, start, &TM__vI9aZNKIcImom6dDyKXW1ZA_17)) { raiseOverflow(); goto BeforeRet_;};		result = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_17);	}
	LA11_: ;
	}BeforeRet_: ;
	popFrame();	return result;}
