/* Generated by Nim Compiler v1.3.7 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  
/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ {NimStringV2 scheme;
NimStringV2 username;
NimStringV2 password;
NimStringV2 hostname;
NimStringV2 port;
NimStringV2 path;
NimStringV2 query;
NimStringV2 anchor;
NIM_BOOL opaque;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];

/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, resetUri__6wZ9cdrNwSrw8xkgtsNgsVQ)(tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* uri);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, parsePath__0TsSB8FdgpD9cp7XiVe8wdA)(NimStringV2 uri, NI* i, tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* result);
static N_INLINE(NI, parseUntil__yxs3WjxMSDtXEyiLC9aqFCAparseutils)(NimStringV2 s, NimStringV2* token, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw until, NI start);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, fastSubstr__a88zu6ztJ3SBDTHcnqFjsg)(NimStringV2 s, NimStringV2* token, NI start, NI length);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringV2 a, NimStringV2 b);
N_LIB_PRIVATE N_NIMCALL(void, parseAuthority__zi1fIQvZNRFlvZX648raeA)(NimStringV2 authority, tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* result);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
static N_INLINE(NI, parseWhile__aIOGZyeHx2rHC71Dcc2SCwparseutils)(NimStringV2 s, NimStringV2* token, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw validChars, NI start);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__VzbRQH9cb1xm1tSKH4PwBSw_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_3 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_4 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_5 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_6 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_7 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_8 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_9 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_10 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__VzbRQH9cb1xm1tSKH4PwBSw_13 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__VzbRQH9cb1xm1tSKH4PwBSw_15 = { 6 | NIM_STRLIT_FLAG, "mailto" };
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_16 = {6, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_15};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__VzbRQH9cb1xm1tSKH4PwBSw_21 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__VzbRQH9cb1xm1tSKH4PwBSw_27 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x68, 0xff, 0x03,
0xfe, 0xff, 0xff, 0x07, 0xfe, 0xff, 0xff, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__VzbRQH9cb1xm1tSKH4PwBSw_33 = {0, (NimStrPayload*)&TM__VzbRQH9cb1xm1tSKH4PwBSw_2};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__VzbRQH9cb1xm1tSKH4PwBSw_34 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x80, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;

/* section: NIM_merge_VARS */
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_THREADVAR TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;

/* section: NIM_merge_PROCS */

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OydxUV9ad0I3qVcqasXV7RQ)(tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* dest, tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* src) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).scheme.p != (*src).scheme.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).scheme));
	}(*dest).scheme.len = (*src).scheme.len; (*dest).scheme.p = (*src).scheme.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).username.p != (*src).username.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).username));
	}(*dest).username.len = (*src).username.len; (*dest).username.p = (*src).username.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).password.p != (*src).password.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).password));
	}(*dest).password.len = (*src).password.len; (*dest).password.p = (*src).password.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).hostname.p != (*src).hostname.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).hostname));
	}(*dest).hostname.len = (*src).hostname.len; (*dest).hostname.p = (*src).hostname.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).port.p != (*src).port.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).port));
	}(*dest).port.len = (*src).port.len; (*dest).port.p = (*src).port.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).path.p != (*src).path.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).path));
	}(*dest).path.len = (*src).path.len; (*dest).path.p = (*src).path.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).query.p != (*src).query.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).query));
	}(*dest).query.len = (*src).query.len; (*dest).query.p = (*src).query.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((*dest).anchor.p != (*src).anchor.p) {
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).anchor));
	}(*dest).anchor.len = (*src).anchor.len; (*dest).anchor.p = (*src).anchor.p;
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	(*dest).opaque = (*src).opaque;}

#line 22 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory)(void* a, int v, NI size) {	void* T1_;
#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 24 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 414 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 415 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);	return result;}

#line 33 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"

#line 34 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/memory.nim"
	nimSetMem__zxfKBYntu9cBapkhrCOk1fgmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 544 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 545 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA3_;

#line 546 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 549 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 551 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 552 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	{
#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"

#line 553 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}

#line 86 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 87 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/excpt.nim"
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}

#line 199 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
N_LIB_PRIVATE N_NIMCALL(tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ, initUri__zcwd3ynrfDQcP9c8k9cEeg9aQ)(void) {	tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ result;	nimfr_("initUri", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ));
#line 208 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(208, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ));	result.scheme = TM__VzbRQH9cb1xm1tSKH4PwBSw_3;	result.username = TM__VzbRQH9cb1xm1tSKH4PwBSw_4;	result.password = TM__VzbRQH9cb1xm1tSKH4PwBSw_5;	result.hostname = TM__VzbRQH9cb1xm1tSKH4PwBSw_6;	result.port = TM__VzbRQH9cb1xm1tSKH4PwBSw_7;	result.path = TM__VzbRQH9cb1xm1tSKH4PwBSw_8;	result.query = TM__VzbRQH9cb1xm1tSKH4PwBSw_9;	result.anchor = TM__VzbRQH9cb1xm1tSKH4PwBSw_10;	popFrame();	return result;}

#line 211 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
N_LIB_PRIVATE N_NIMCALL(void, resetUri__6wZ9cdrNwSrw8xkgtsNgsVQ)(tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* uri) {	nimfr_("resetUri", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(214, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	setLengthStrV2((&(*uri).scheme), ((NI) 0));
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	setLengthStrV2((&(*uri).username), ((NI) 0));
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	setLengthStrV2((&(*uri).password), ((NI) 0));
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	setLengthStrV2((&(*uri).hostname), ((NI) 0));
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	setLengthStrV2((&(*uri).port), ((NI) 0));
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	setLengthStrV2((&(*uri).path), ((NI) 0));
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	setLengthStrV2((&(*uri).query), ((NI) 0));
#line 214 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	setLengthStrV2((&(*uri).anchor), ((NI) 0));
#line 216 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(216, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	(*uri).opaque = NIM_FALSE;	popFrame();}

#line 317 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
static N_INLINE(NI, parseUntil__yxs3WjxMSDtXEyiLC9aqFCAparseutils)(NimStringV2 s, NimStringV2* token, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw until, NI start) {	NI result;	NI i;	NI TM__VzbRQH9cb1xm1tSKH4PwBSw_12;NIM_BOOL* nimErr_;	nimfr_("parseUntil", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 330 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(330, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	i = start;	{
#line 331 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		nimln_(331, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");		while (1) {			NIM_BOOL T3_;			NI TM__VzbRQH9cb1xm1tSKH4PwBSw_11;
#line 331 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T3_ = (NIM_BOOL)0;
#line 331 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 331 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T3_ = (i < s.len);			if (!(T3_)) goto LA4_;

#line 331 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 331 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}			T3_ = !(((until[(NU)(((NU8)(s.p->data[i])))>>3] &(1U<<((NU)(((NU8)(s.p->data[i])))&7U)))!=0));			LA4_: ;
			if (!T3_) goto LA2;

#line 331 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if (nimAddInt(i, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_11)) { raiseOverflow(); goto BeforeRet_;};			i = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_11);		} LA2: ;
	}

#line 332 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(332, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 332 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	if (nimSubInt(i, start, &TM__VzbRQH9cb1xm1tSKH4PwBSw_12)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_12);
#line 333 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(333, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 333 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	fastSubstr__a88zu6ztJ3SBDTHcnqFjsg(s, token, start, result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 55 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {	NI TM__VzbRQH9cb1xm1tSKH4PwBSw_17;	NI TM__VzbRQH9cb1xm1tSKH4PwBSw_18;{
#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"

#line 57 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	prepareAdd(s, ((NI) 1));

#line 58 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	(*(*s).p).data[(*s).len] = c;
#line 59 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	if (nimAddInt((*s).len, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_17)) { raiseOverflow(); goto BeforeRet_;};
#line 59 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	(*(*s).p).data[(NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_17)] = 0;
#line 60 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/strs_v2.nim"
	if (nimAddInt((*s).len, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_18)) { raiseOverflow(); goto BeforeRet_;};	(*s).len = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_18);	}BeforeRet_: ;
}

#line 154 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
N_LIB_PRIVATE N_NIMCALL(void, parseAuthority__zi1fIQvZNRFlvZX648raeA)(NimStringV2 authority, tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* result) {	NI i;	NIM_BOOL inPort;	NIM_BOOL inIPv6;	nimfr_("parseAuthority", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");{
#line 155 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(155, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	i = ((NI) 0);
#line 156 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(156, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	inPort = NIM_FALSE;
#line 157 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(157, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	inIPv6 = NIM_FALSE;	{
#line 158 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(158, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		while (1) {			NI TM__VzbRQH9cb1xm1tSKH4PwBSw_19;
#line 158 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 158 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			if (!(i < authority.len)) goto LA2;

#line 159 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			nimln_(159, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");			if ((NU)(i) >= (NU)authority.len){ raiseIndexError2(i,authority.len-1); goto BeforeRet_;}			switch (((NU8)(authority.p->data[i]))) {
			case 64:
			{				NimStringV2 T4_;				NimStringV2 T5_;
#line 161 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(161, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				T4_.len = 0; T4_.p = NIM_NIL;				T4_ = (*result).password;				(*result).password = (*result).port;				(*result).port = T4_;
#line 162 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(162, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				setLengthStrV2((&(*result).port), ((NI) 0));
#line 163 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(163, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				T5_.len = 0; T5_.p = NIM_NIL;				T5_ = (*result).username;				(*result).username = (*result).hostname;				(*result).hostname = T5_;
#line 164 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(164, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				setLengthStrV2((&(*result).hostname), ((NI) 0));
#line 165 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(165, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				inPort = NIM_FALSE;			}
			break;
			case 58:
			{
#line 167 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(167, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				{					if (!inIPv6) goto LA9_;

#line 168 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
					nimln_(168, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");					if ((NU)(i) >= (NU)authority.len){ raiseIndexError2(i,authority.len-1); goto BeforeRet_;}					nimAddCharV1((&(*result).hostname), authority.p->data[i]);				}
				goto LA7_;
				LA9_: ;
				{
#line 170 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
					nimln_(170, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");					inPort = NIM_TRUE;				}
				LA7_: ;
			}
			break;
			case 91:
			{
#line 172 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(172, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				inIPv6 = NIM_TRUE;			}
			break;
			case 93:
			{
#line 174 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(174, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				inIPv6 = NIM_FALSE;			}
			break;
			default:
			{
#line 176 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
				nimln_(176, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");				{					if (!inPort) goto LA17_;

#line 177 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
					nimln_(177, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");					if ((NU)(i) >= (NU)authority.len){ raiseIndexError2(i,authority.len-1); goto BeforeRet_;}					nimAddCharV1((&(*result).port), authority.p->data[i]);				}
				goto LA15_;
				LA17_: ;
				{
#line 179 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
					nimln_(179, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");					if ((NU)(i) >= (NU)authority.len){ raiseIndexError2(i,authority.len-1); goto BeforeRet_;}					nimAddCharV1((&(*result).hostname), authority.p->data[i]);				}
				LA15_: ;
			}
			break;
			}

#line 180 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			nimln_(180, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");			if (nimAddInt(i, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_19)) { raiseOverflow(); goto BeforeRet_;};			i = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_19);		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();}

#line 182 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
N_LIB_PRIVATE N_NIMCALL(void, parsePath__0TsSB8FdgpD9cp7XiVe8wdA)(NimStringV2 uri, NI* i, tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* result) {	NI T1_;	NI TM__VzbRQH9cb1xm1tSKH4PwBSw_14;NIM_BOOL* nimErr_;	nimfr_("parsePath", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");{nimErr_ = nimErrorFlag();
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(184, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 184 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	T1_ = (NI)0;	T1_ = parseUntil__yxs3WjxMSDtXEyiLC9aqFCAparseutils(uri, (&(*result).path), TM__VzbRQH9cb1xm1tSKH4PwBSw_13, (*i));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt((*i), T1_, &TM__VzbRQH9cb1xm1tSKH4PwBSw_14)) { raiseOverflow(); goto BeforeRet_;};	(*i) = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_14);
#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(187, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	{		NI T4_;
#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 187 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T4_ = (NI)0;		T4_ = nsuCmpIgnoreCase((*result).scheme, TM__VzbRQH9cb1xm1tSKH4PwBSw_16);		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (!(T4_ == ((NI) 0))) goto LA5_;

#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(188, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 188 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		parseAuthority__zi1fIQvZNRFlvZX648raeA((*result).path, result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 189 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(189, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		setLengthStrV2((&(*result).path), ((NI) 0));	}
	LA5_: ;

#line 191 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(191, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	{		NIM_BOOL T9_;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_20;		NI T13_;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_22;
#line 191 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T9_ = (NIM_BOOL)0;
#line 191 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 191 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T9_ = ((*i) < uri.len);		if (!(T9_)) goto LA10_;

#line 191 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if ((NU)((*i)) >= (NU)uri.len){ raiseIndexError2((*i),uri.len-1); goto BeforeRet_;}		T9_ = ((NU8)(uri.p->data[(*i)]) == (NU8)(63));		LA10_: ;
		if (!T9_) goto LA11_;

#line 192 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(192, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		if (nimAddInt((*i), ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_20)) { raiseOverflow(); goto BeforeRet_;};		(*i) = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_20);
#line 193 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(193, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 193 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 193 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T13_ = (NI)0;		T13_ = parseUntil__yxs3WjxMSDtXEyiLC9aqFCAparseutils(uri, (&(*result).query), TM__VzbRQH9cb1xm1tSKH4PwBSw_21, (*i));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (nimAddInt((*i), T13_, &TM__VzbRQH9cb1xm1tSKH4PwBSw_22)) { raiseOverflow(); goto BeforeRet_;};		(*i) = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_22);	}
	LA11_: ;

#line 195 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(195, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	{		NIM_BOOL T16_;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_23;		tySet_tyChar__nmiMWKVIe46vacnhAFrQvw T20_;		NI T21_;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_24;
#line 195 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T16_ = (NIM_BOOL)0;
#line 195 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 195 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T16_ = ((*i) < uri.len);		if (!(T16_)) goto LA17_;

#line 195 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if ((NU)((*i)) >= (NU)uri.len){ raiseIndexError2((*i),uri.len-1); goto BeforeRet_;}		T16_ = ((NU8)(uri.p->data[(*i)]) == (NU8)(35));		LA17_: ;
		if (!T16_) goto LA18_;

#line 196 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(196, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		if (nimAddInt((*i), ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_23)) { raiseOverflow(); goto BeforeRet_;};		(*i) = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_23);
#line 197 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(197, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 197 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimZeroMem(T20_, sizeof(tySet_tyChar__nmiMWKVIe46vacnhAFrQvw));
#line 197 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T21_ = (NI)0;		T21_ = parseUntil__yxs3WjxMSDtXEyiLC9aqFCAparseutils(uri, (&(*result).anchor), T20_, (*i));		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (nimAddInt((*i), T21_, &TM__VzbRQH9cb1xm1tSKH4PwBSw_24)) { raiseOverflow(); goto BeforeRet_;};		(*i) = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_24);	}
	LA18_: ;
	}BeforeRet_: ;
	popFrame();}

#line 382 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
static N_INLINE(NI, parseWhile__aIOGZyeHx2rHC71Dcc2SCwparseutils)(NimStringV2 s, NimStringV2* token, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw validChars, NI start) {	NI result;	NI i;	NI TM__VzbRQH9cb1xm1tSKH4PwBSw_26;NIM_BOOL* nimErr_;	nimfr_("parseWhile", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 393 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(393, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");	i = start;	{
#line 394 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
		nimln_(394, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");		while (1) {			NIM_BOOL T3_;			NI TM__VzbRQH9cb1xm1tSKH4PwBSw_25;
#line 394 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T3_ = (NIM_BOOL)0;
#line 394 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"

#line 394 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			T3_ = (i < s.len);			if (!(T3_)) goto LA4_;

#line 394 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if ((NU)(i) >= (NU)s.len){ raiseIndexError2(i,s.len-1); goto BeforeRet_;}			T3_ = ((validChars[(NU)(((NU8)(s.p->data[i])))>>3] &(1U<<((NU)(((NU8)(s.p->data[i])))&7U)))!=0);			LA4_: ;
			if (!T3_) goto LA2;

#line 394 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
			if (nimAddInt(i, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_25)) { raiseOverflow(); goto BeforeRet_;};			i = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_25);		} LA2: ;
	}

#line 395 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(395, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 395 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	if (nimSubInt(i, start, &TM__VzbRQH9cb1xm1tSKH4PwBSw_26)) { raiseOverflow(); goto BeforeRet_;};	result = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_26);
#line 396 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	nimln_(396, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.ni"
"m");
#line 396 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/parseutils.nim"
	fastSubstr__a88zu6ztJ3SBDTHcnqFjsg(s, token, start, result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}

#line 218 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
N_LIB_PRIVATE N_NIMCALL(void, parseUri__2Afz5k9c4YIkP0o0kpbe9cvQ)(NimStringV2 uri, tyObject_Uri__j49bukNPrq747O1GRd4Ng9bQ* result) {	NI i;	NIM_BOOL doubleSlash;	NIM_BOOL T1_;	NI T13_;	NI TM__VzbRQH9cb1xm1tSKH4PwBSw_28;NIM_BOOL* nimErr_;	nimfr_("parseUri", "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");{nimErr_ = nimErrorFlag();
#line 230 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(230, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 230 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	resetUri__6wZ9cdrNwSrw8xkgtsNgsVQ(result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 232 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(232, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	i = ((NI) 0);
#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(235, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	T1_ = (NIM_BOOL)0;
#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	T1_ = (((NI) 1) < uri.len);	if (!(T1_)) goto LA2_;

#line 235 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	if ((NU)(((NI) 1)) >= (NU)uri.len){ raiseIndexError2(((NI) 1),uri.len-1); goto BeforeRet_;}	T1_ = ((NU8)(uri.p->data[((NI) 1)]) == (NU8)(47));	LA2_: ;
	doubleSlash = T1_;
#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(236, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	{		NIM_BOOL T5_;
#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T5_ = (NIM_BOOL)0;
#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T5_ = (i < uri.len);		if (!(T5_)) goto LA6_;

#line 236 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if ((NU)(i) >= (NU)uri.len){ raiseIndexError2(i,uri.len-1); goto BeforeRet_;}		T5_ = ((NU8)(uri.p->data[i]) == (NU8)(47));		LA6_: ;
		if (!T5_) goto LA7_;

#line 238 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(238, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		{
#line 238 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			if (!!(doubleSlash)) goto LA11_;

#line 239 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			nimln_(239, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 239 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			parsePath__0TsSB8FdgpD9cp7XiVe8wdA(uri, (&i), result);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 240 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			nimln_(240, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");			goto BeforeRet_;
		}
		LA11_: ;
	}
	LA7_: ;

#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(243, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 243 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	T13_ = (NI)0;	T13_ = parseWhile__aIOGZyeHx2rHC71Dcc2SCwparseutils(uri, (&(*result).scheme), TM__VzbRQH9cb1xm1tSKH4PwBSw_27, i);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimAddInt(i, T13_, &TM__VzbRQH9cb1xm1tSKH4PwBSw_28)) { raiseOverflow(); goto BeforeRet_;};	i = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_28);
#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(244, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	{		NIM_BOOL T16_;		NIM_BOOL T17_;
#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T16_ = (NIM_BOOL)0;
#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T17_ = (NIM_BOOL)0;
#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T17_ = (uri.len <= i);		if (T17_) goto LA18_;

#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if ((NU)(i) >= (NU)uri.len){ raiseIndexError2(i,uri.len-1); goto BeforeRet_;}		T17_ = !(((NU8)(uri.p->data[i]) == (NU8)(58)));		LA18_: ;
		T16_ = T17_;		if (!(T16_)) goto LA19_;

#line 244 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T16_ = !(doubleSlash);		LA19_: ;
		if (!T16_) goto LA20_;

#line 246 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(246, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		i = ((NI) 0);
#line 247 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(247, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		setLengthStrV2((&(*result).scheme), ((NI) 0));
#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(248, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 248 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		parsePath__0TsSB8FdgpD9cp7XiVe8wdA(uri, (&i), result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 249 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(249, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		goto BeforeRet_;
	}
	LA20_: ;

#line 250 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(250, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	{		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_29;
#line 250 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if (!!(doubleSlash)) goto LA24_;

#line 251 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(251, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		if (nimAddInt(i, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_29)) { raiseOverflow(); goto BeforeRet_;};		i = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_29);	}
	LA24_: ;

#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(254, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");	{		NIM_BOOL T28_;		NIM_BOOL T29_;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_30;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_31;		NimStringV2 authority;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_32;		NI T34_;		NI TM__VzbRQH9cb1xm1tSKH4PwBSw_35;
#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T28_ = (NIM_BOOL)0;
#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T29_ = (NIM_BOOL)0;
#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if (nimAddInt(i, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_30)) { raiseOverflow(); goto BeforeRet_;};
#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T29_ = ((NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_30) < uri.len);		if (!(T29_)) goto LA30_;

#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if ((NU)(i) >= (NU)uri.len){ raiseIndexError2(i,uri.len-1); goto BeforeRet_;}		T29_ = ((NU8)(uri.p->data[i]) == (NU8)(47));		LA30_: ;
		T28_ = T29_;		if (!(T28_)) goto LA31_;

#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 254 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		if (nimAddInt(i, ((NI) 1), &TM__VzbRQH9cb1xm1tSKH4PwBSw_31)) { raiseOverflow(); goto BeforeRet_;};		if ((NU)((NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_31)) >= (NU)uri.len){ raiseIndexError2((NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_31),uri.len-1); goto BeforeRet_;}		T28_ = ((NU8)(uri.p->data[(NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_31)]) == (NU8)(47));		LA31_: ;
		if (!T28_) goto LA32_;
		authority.len = 0; authority.p = NIM_NIL;
#line 255 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(255, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		if (nimAddInt(i, ((NI) 2), &TM__VzbRQH9cb1xm1tSKH4PwBSw_32)) { raiseOverflow(); goto BeforeRet_;};		i = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_32);
#line 256 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(256, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		authority = TM__VzbRQH9cb1xm1tSKH4PwBSw_33;
#line 257 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(257, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 257 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 257 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		T34_ = (NI)0;		T34_ = parseUntil__yxs3WjxMSDtXEyiLC9aqFCAparseutils(uri, (&authority), TM__VzbRQH9cb1xm1tSKH4PwBSw_34, i);		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		if (nimAddInt(i, T34_, &TM__VzbRQH9cb1xm1tSKH4PwBSw_35)) { raiseOverflow(); goto BeforeRet_;};		i = (NI)(TM__VzbRQH9cb1xm1tSKH4PwBSw_35);
#line 258 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(258, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		{
#line 258 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"

#line 258 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			if (!(((NI) 0) < authority.len)) goto LA37_;

#line 259 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			nimln_(259, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 259 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
			parseAuthority__zi1fIQvZNRFlvZX648raeA(authority, result);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		}
		LA37_: ;

#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		nimln_(49, "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim");
#line 49 "/Users/elcritch/.asdf/installs/nim/devel/lib/system/fatal.nim"
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&authority));
	}
	goto LA26_;
	LA32_: ;
	{
#line 261 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
		nimln_(261, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");		(*result).opaque = NIM_TRUE;	}
	LA26_: ;

#line 264 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	nimln_(264, "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim");
#line 264 "/Users/elcritch/.asdf/installs/nim/devel/lib/pure/uri.nim"
	parsePath__0TsSB8FdgpD9cp7XiVe8wdA(uri, (&i), result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
