import ../consts

type EspError* = enum
  Fail = ESP_FAIL
  Ok = ESP_OK
  NO_MEM = ESP_ERR_NO_MEM
  INVALID_ARG = ESP_ERR_INVALID_ARG
  INVALID_STATE = ESP_ERR_INVALID_STATE
  INVALID_SIZE = ESP_ERR_INVALID_SIZE
  NOT_FOUND = ESP_ERR_NOT_FOUND
  NOT_SUPPORTED = ESP_ERR_NOT_SUPPORTED
  TIMEOUT = ESP_ERR_TIMEOUT
  INVALID_RESPONSE = ESP_ERR_INVALID_RESPONSE
  INVALID_CRC = ESP_ERR_INVALID_CRC
  INVALID_VERSION = ESP_ERR_INVALID_VERSION
  INVALID_MAC = ESP_ERR_INVALID_MAC
  WIFI_BASE = ESP_ERR_WIFI_BASE
  MESH_BASE = ESP_ERR_MESH_BASE
  FLASH_BASE = ESP_ERR_FLASH_BASE
