on:
  pull_request:
    branches:
    - "*"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nimversion:
          - '2.x'
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nimversion }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Deps
      run: |
        nimble install atlas@\#head
        atlas install --feature:examples

    - name: Build Tests
      run: |
        nim test

    - name: Install ESP-IDF
      uses: espressif/install-esp-idf-action@v1
      with:
        version: "v5.5"

    - name: Check esp-idf
      run: |
        idf.py --version

    - name: Build Tests
      run: |
        nim testExamples
